"""
Customer Enquiry views
"""

from django.views.generic import DetailView, TemplateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import HttpResponse
from django.db.models import Q, OuterRef, Subquery, CharField, Value
from django.db.models.functions import Concat, Coalesce
from django.db import transaction
from datetime import datetime
from io import BytesIO

from ..models import (
    SdCustMaster, SdCustEnquiryMaster, SdCustEnquiryAttachMaster,
    SdCustQuotationMaster, SdCustPoMaster, SdCustWorkorderMaster
)
from ..forms import CustomerEnquiryForm, CustomerEnquiryAttachmentForm
from .base import FinancialYearUserMixin
from core.mixins import CompanyFinancialYearMixin
from sys_admin.models import (
    Tblcountry, TblfinancialMaster as FinancialYear
)
from human_resource.models import TblhrOfficestaff

class CustomerEnquiryView(LoginRequiredMixin, View):
    """
    Handles CRUD operations for Customer Enquiries.
    """
    def get(self, request, enqid=None):
        if enqid:
            enquiry = get_object_or_404(SdCustEnquiryMaster, enqid=enqid)
            form = CustomerEnquiryForm(instance=enquiry)
            return render(request, 'sales_distribution/enquiry_form.html', {'form': form, 'enquiry': enquiry})
        else:
            # Subquery to get financial year name
            finyear_subquery = FinancialYear.objects.filter(
                finyearid=OuterRef('finyearid')
            ).values('finyear')[:1]

            # Subquery to get employee name from HR OfficeStaff (Title.EmployeeName format)
            # Matches ASP.NET logic: "Title+'.'+EmployeeName" from tblHR_OfficeStaff where EmpId = SessionId
            employee_subquery = TblhrOfficestaff.objects.filter(
                empid=OuterRef('sessionid')
            ).annotate(
                full_name=Concat('title', Value('.'), 'employeename', output_field=CharField())
            ).values('full_name')[:1]

            # Subquery to get username from Django User table (fallback for newer records)
            user_subquery = User.objects.filter(
                id=OuterRef('sessionid')
            ).values('username')[:1]

            # Annotate queryset with financial year and generated by
            # Use Coalesce to check HR OfficeStaff first, then fallback to Django User
            enquiries = SdCustEnquiryMaster.objects.annotate(
                finyear_name=Subquery(finyear_subquery),
                generated_by=Coalesce(
                    Subquery(employee_subquery),
                    Subquery(user_subquery)
                )
            ).order_by('-enqid')

            search = request.GET.get('search', '')
            if search:
                enquiries = enquiries.filter(
                    Q(customername__icontains=search) |
                    Q(enquiryfor__icontains=search) |
                    Q(customerid__icontains=search)
                )
            return render(request, 'sales_distribution/enquiry_list.html', {'enquiries': enquiries, 'form': CustomerEnquiryForm()})

    def post(self, request, enqid=None):
        form = CustomerEnquiryForm(request.POST)
        if form.is_valid():
            enquiry = form.save(commit=False)
            now = datetime.now()
            enquiry.sysdate = now.strftime('%d-%m-%Y')  # FIXED: Date format to match ASP.NET
            enquiry.systime = now.strftime('%H:%M:%S')
            enquiry.sessionid = str(request.user.id)

            # FIXED: Get compid from session instead of hardcoding
            enquiry.compid = request.session.get('compid')
            if not enquiry.compid:
                messages.error(request, 'Company ID not found in session. Please log in again.')
                return redirect('core:login')

            # Get finyearid from session, or use latest active financial year
            enquiry.finyearid = request.session.get('finyearid')
            if not enquiry.finyearid:
                # Fallback: Get latest active financial year (highest finyearid with flag=1)
                current_fy = FinancialYear.objects.filter(flag=1).order_by('-finyearid').first()
                if current_fy:
                    enquiry.finyearid = current_fy.finyearid
                else:
                    # If no active FY, get the latest one
                    latest_fy = FinancialYear.objects.order_by('-finyearid').first()
                    enquiry.finyearid = latest_fy.finyearid if latest_fy else 1
            enquiry.postatus = 0
            if not enquiry.customerid:
                enquiry.customerid = None
            enquiry.save()
            messages.success(request, f'Enquiry created successfully for {enquiry.customername}.')
            return redirect('sales_distribution:enquiry-list')
        return render(request, 'sales_distribution/enquiry_form.html', {'form': form})

    def put(self, request, enqid):
        enquiry = get_object_or_404(SdCustEnquiryMaster, enqid=enqid)
        form = CustomerEnquiryForm(request.POST, instance=enquiry)
        if form.is_valid():
            customer = form.cleaned_data['customer']
            enquiry.customerid = customer.customerid
            enquiry.customername = customer.customername
            form.save()
            messages.success(request, 'Enquiry updated successfully.')
            return redirect('sales_distribution:enquiry-list')
        return render(request, 'sales_distribution/enquiry_form.html', {'form': form, 'enquiry': enquiry})

    def delete(self, request, enqid):
        enquiry = get_object_or_404(SdCustEnquiryMaster, enqid=enqid)
        enquiry_name = enquiry.customername
        enquiry.delete()  # FIXED: Was enquiry.save()
        if request.headers.get('HX-Request'):
            return HttpResponse(status=204)
        messages.success(request, f'Enquiry {enquiry_name} deleted successfully.')
        return redirect('sales_distribution:enquiry-list')


class CustomerEnquiryCreateView(LoginRequiredMixin, View):
    """
    Handles customer enquiry creation.
    """
    def get(self, request):
        form = CustomerEnquiryForm()
        return render(request, 'sales_distribution/enquiry_form.html', {'form': form})

    def post(self, request):
        form = CustomerEnquiryForm(request.POST)
        if form.is_valid():
            enquiry = form.save(commit=False)
            now = datetime.now()
            enquiry.sysdate = now.strftime('%d-%m-%Y')  # FIXED: Date format to match ASP.NET
            enquiry.systime = now.strftime('%H:%M:%S')
            enquiry.sessionid = str(request.user.id)

            # FIXED: Get compid from session with fallback to 1
            enquiry.compid = request.session.get('compid', 1)

            # Get finyearid from session, or use latest active financial year
            enquiry.finyearid = request.session.get('finyearid')
            if not enquiry.finyearid:
                # Fallback: Get latest active financial year (highest finyearid with flag=1)
                current_fy = FinancialYear.objects.filter(flag=1).order_by('-finyearid').first()
                if current_fy:
                    enquiry.finyearid = current_fy.finyearid
                else:
                    # If no active FY, get the latest one
                    latest_fy = FinancialYear.objects.order_by('-finyearid').first()
                    enquiry.finyearid = latest_fy.finyearid if latest_fy else 1
            enquiry.postatus = 0
            if not enquiry.customerid:
                enquiry.customerid = None
            enquiry.save()
            messages.success(request, f'Enquiry created successfully for {enquiry.customername}.')
            return redirect('sales_distribution:enquiry-list')
        return render(request, 'sales_distribution/enquiry_form.html', {'form': form})


class CustomerEnquiryDetailView(LoginRequiredMixin, DetailView):
    """
    View customer enquiry details.
    Converted from: aspnet/Module/SalesDistribution/Transactions/CustEnquiry_Print_Details.aspx
    """
    model = SdCustEnquiryMaster
    template_name = 'sales_distribution/enquiry_detail.html'
    context_object_name = 'enquiry'
    pk_url_kwarg = 'enqid'
    
    def get_context_data(self, **kwargs):
        """Add attachments to context."""
        context = super().get_context_data(**kwargs)
        context['attachments'] = SdCustEnquiryAttachMaster.objects.filter(enqid=self.object.enqid)
        return context





class CustomerEnquiryPrintView(LoginRequiredMixin, DetailView):
    """
    Generate professional PDF for Customer Enquiry.
    Converted from: D:/inetpub/NewERP/Module/SalesDistribution/Transactions/CustEnquiry_Print_Details.aspx

    Note: Uses xhtml2pdf instead of Crystal Reports for Windows compatibility
    """
    model = SdCustEnquiryMaster
    pk_url_kwarg = 'enqid'
    template_name = 'sales_distribution/enquiry_print_pdf.html'

    def get_context_data(self, **kwargs):
        from django.conf import settings

        context = super().get_context_data(**kwargs)
        enquiry = self.get_object()

        # Get financial year name
        finyear_name = None
        try:
            finyear = FinancialYear.objects.get(pk=enquiry.finyearid)
            finyear_name = finyear.finyear
        except FinancialYear.DoesNotExist:
            finyear_name = str(enquiry.finyearid)

        # Get employee/user name from sessionid
        employee_name = None
        try:
            user = User.objects.get(pk=int(enquiry.sessionid))
            employee_name = user.username
        except (User.DoesNotExist, ValueError):
            employee_name = enquiry.sessionid

        context.update({
            'enquiry': enquiry,
            'finyear_name': finyear_name,
            'employee_name': employee_name,
            'company_name': 'Synergytech Automation Pvt. Ltd.',
            'company_address': 'Pune, Maharashtra, India',
            'company_phone': '+91-XXX-XXXXXXX',
            'company_email': 'sales@synergytechs.com',
            'company_website': 'www.synergytechs.com',
        })

        return context

    def render_to_response(self, context, **response_kwargs):
        """Render as PDF using xhtml2pdf"""
        from xhtml2pdf import pisa
        from django.template.loader import render_to_string
        from io import BytesIO

        # Render HTML template
        html_string = render_to_string(self.template_name, context)

        # Generate PDF
        result = BytesIO()
        pdf = pisa.pisaDocument(BytesIO(html_string.encode("UTF-8")), result)

        if pdf.err:
            return HttpResponse(f'Error generating PDF: {pdf.err}', content_type='text/html')

        # Return as PDF response
        enq_no = f'ENQ_{context["enquiry"].enqid}'
        filename = f'Customer_Enquiry_{enq_no}.pdf'

        response = HttpResponse(result.getvalue(), content_type='application/pdf')
        response['Content-Disposition'] = f'inline; filename="{filename}"'

        return response




class CustomerEnquiryConvertView(LoginRequiredMixin, CompanyFinancialYearMixin, TemplateView):
    """
    Convert customer enquiries to customers.
    Shows unconverted enquiries (Flag=0 or customerid is None/ENQ-CUST pattern)
    with search functionality and checkbox-based conversion.
    """
    template_name = 'sales_distribution/enquiry_convert.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get search parameters
        search_type = self.request.GET.get('search_type', 'select')
        search_value = self.request.GET.get('search_value', '')
        enq_id = self.request.GET.get('enq_id', '')

        # Base queryset - unconverted enquiries only
        compid = self.request.session.get('compid', 1)
        finyearid = self.request.session.get('finyearid', 1)

        # Get unconverted enquiries: flag=0 or flag=None
        enquiries = SdCustEnquiryMaster.objects.filter(
            compid=compid,
            finyearid__lte=finyearid
        ).filter(
            Q(flag=0) | Q(flag__isnull=True)
        ).select_related().order_by('-enqid')

        # Apply search filters
        if search_type == 'customer_name' and search_value:
            # Extract customer code if format is "Name [CODE]"
            if '[' in search_value and ']' in search_value:
                code = search_value[search_value.find('[')+1:search_value.find(']')]
                enquiries = enquiries.filter(customerid=code)
            else:
                enquiries = enquiries.filter(customername__icontains=search_value)
        elif search_type == 'enq_no' and enq_id:
            enquiries = enquiries.filter(enqid=enq_id)

        # Get related data for each enquiry
        enquiry_list = []
        for enq in enquiries:
            # Get financial year name
            finyear_name = '-'
            if enq.finyearid:
                try:
                    finyear = TblfinancialMaster.objects.get(finyearid=enq.finyearid)
                    finyear_name = finyear.finyear
                except TblfinancialMaster.DoesNotExist:
                    pass

            # Get employee name
            employee_name = '-'
            if enq.sessionid:
                try:
                    user = User.objects.get(pk=int(enq.sessionid))
                    employee_name = user.get_full_name() or user.username
                except (User.DoesNotExist, ValueError):
                    employee_name = enq.sessionid

            enquiry_list.append({
                'enquiry': enq,
                'finyear_name': finyear_name,
                'employee_name': employee_name,
            })

        context.update({
            'enquiries': enquiry_list,
            'search_type': search_type,
            'search_value': search_value,
            'enq_id': enq_id,
        })

        return context

    def post(self, request, *args, **kwargs):
        """Handle enquiry conversion"""
        enq_id = request.POST.get('enq_id')
        redirect_to_detail = request.POST.get('redirect_to_detail', False)

        if not enq_id:
            messages.error(request, 'Enquiry ID is required.')
            return redirect('sales_distribution:enquiry-convert')

        try:
            # Use the service to convert enquiry
            result = CustomerService.convert_enquiry_to_customer(
                enquiry_id=enq_id,
                user_id=request.user.id,
                compid=request.session.get('compid', 1),
                finyearid=request.session.get('finyearid', 1)
            )

            messages.success(request, result['message'])

            # Redirect to enquiry detail if coming from detail page
            if redirect_to_detail or request.META.get('HTTP_REFERER', '').endswith(f'/enquiry/{enq_id}/'):
                return redirect('sales_distribution:enquiry-detail', enqid=enq_id)

            # If HTMX request, reload the list
            if request.headers.get('HX-Request'):
                return redirect('sales_distribution:enquiry-convert')

        except ValidationError as e:
            messages.error(request, str(e))
            # Redirect back to detail page if error
            if redirect_to_detail or request.META.get('HTTP_REFERER', '').endswith(f'/enquiry/{enq_id}/'):
                return redirect('sales_distribution:enquiry-detail', enqid=enq_id)
        except Exception as e:
            messages.error(request, f'Error converting enquiry: {str(e)}')
            # Redirect back to detail page if error
            if redirect_to_detail or request.META.get('HTTP_REFERER', '').endswith(f'/enquiry/{enq_id}/'):
                return redirect('sales_distribution:enquiry-detail', enqid=enq_id)

        return redirect('sales_distribution:enquiry-convert')




