# Generated by Django 5.2.7 on 2025-11-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(blank=True, db_column='ItemCode', max_length=255, null=True)),
                ('n', models.CharField(blank=True, db_column='N', max_length=255, null=True)),
            ],
            options={
                'db_table': 'AllItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Allrates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(blank=True, db_column='ItemCode', max_length=255, null=True)),
                ('rate', models.CharField(blank=True, db_column='Rate', max_length=255, null=True)),
                ('discount', models.CharField(blank=True, db_column='Discount', max_length=255, null=True)),
            ],
            options={
                'db_table': 'AllRates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgBomAmd',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(blank=True, db_column='SysDate', max_length=50, null=True)),
                ('systime', models.CharField(blank=True, db_column='SysTime', max_length=50, null=True)),
                ('compid', models.IntegerField(blank=True, db_column='CompId', null=True)),
                ('finyearid', models.IntegerField(blank=True, db_column='FinYearId', null=True)),
                ('sessionid', models.CharField(blank=True, db_column='SessionId', max_length=50, null=True)),
                ('wono', models.TextField(blank=True, db_column='WONo', null=True)),
                ('bomid', models.TextField(blank=True, db_column='BOMId', null=True)),
                ('pid', models.IntegerField(blank=True, db_column='PId', null=True)),
                ('cid', models.IntegerField(blank=True, db_column='CId', null=True)),
                ('itemid', models.IntegerField(blank=True, db_column='ItemId', null=True)),
                ('qty', models.FloatField(blank=True, db_column='Qty', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('uom', models.IntegerField(blank=True, db_column='UOM', null=True)),
                ('amdno', models.IntegerField(blank=True, db_column='AmdNo', null=True)),
            ],
            options={
                'db_table': 'tblDG_BOM_Amd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgBomMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(blank=True, db_column='SysDate', max_length=50, null=True)),
                ('systime', models.CharField(blank=True, db_column='SysTime', max_length=50, null=True)),
                ('compid', models.IntegerField(blank=True, db_column='CompId', null=True)),
                ('finyearid', models.IntegerField(blank=True, db_column='FinYearId', null=True)),
                ('sessionid', models.CharField(blank=True, db_column='SessionId', max_length=50, null=True)),
                ('wono', models.TextField(blank=True, db_column='WONo', null=True)),
                ('equipmentno', models.TextField(blank=True, db_column='EquipmentNo', null=True)),
                ('unitno', models.CharField(blank=True, db_column='UnitNo', max_length=50, null=True)),
                ('partno', models.TextField(blank=True, db_column='PartNo', null=True)),
                ('pid', models.IntegerField(blank=True, db_column='PId', null=True)),
                ('cid', models.IntegerField(blank=True, db_column='CId', null=True)),
                ('qty', models.FloatField(blank=True, db_column='Qty', null=True)),
                ('ecn', models.IntegerField(blank=True, db_column='ECN', null=True)),
                ('ecnflag', models.IntegerField(blank=True, db_column='ECNFlag', null=True)),
                ('amdno', models.IntegerField(db_column='AmdNo')),
                ('revision', models.CharField(db_column='Revision', max_length=50)),
                ('remark', models.TextField(blank=True, db_column='Remark', null=True)),
                ('material', models.TextField(blank=True, db_column='Material', null=True)),
            ],
            options={
                'db_table': 'tblDG_BOM_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgCategoryMaster',
            fields=[
                ('cid', models.AutoField(db_column='CId', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(db_column='SysDate', max_length=50)),
                ('systime', models.CharField(db_column='SysTime', max_length=50)),
                ('compid', models.IntegerField(db_column='CompId')),
                ('finyearid', models.IntegerField(db_column='FinYearId')),
                ('sessinid', models.CharField(db_column='SessinId', max_length=50)),
                ('cname', models.TextField(db_column='CName')),
                ('symbol', models.TextField(db_column='Symbol')),
                ('hassubcat', models.CharField(blank=True, db_column='HasSubCat', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblDG_Category_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgEcnDetails',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('ecnreason', models.IntegerField(blank=True, db_column='ECNReason', null=True)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
            ],
            options={
                'db_table': 'tblDG_ECN_Details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgEcnMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sysdate', models.TextField(db_column='SysDate')),
                ('systime', models.TextField(db_column='SysTime')),
                ('compid', models.IntegerField(db_column='CompId')),
                ('finyearid', models.IntegerField(db_column='FinYearId')),
                ('sessionid', models.TextField(db_column='SessionId')),
                ('itemid', models.IntegerField(blank=True, db_column='ItemId', null=True)),
                ('wono', models.TextField(blank=True, db_column='WONo', null=True)),
                ('pid', models.IntegerField(blank=True, db_column='PId', null=True)),
                ('cid', models.IntegerField(blank=True, db_column='CId', null=True)),
                ('flag', models.IntegerField(blank=True, db_column='Flag', null=True)),
            ],
            options={
                'db_table': 'tblDG_ECN_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgEcnReason',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('compid', models.IntegerField(blank=True, db_column='CompId', null=True)),
                ('types', models.TextField(blank=True, db_column='Types', null=True)),
            ],
            options={
                'db_table': 'tblDG_ECN_Reason',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgGunrailBomMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('equipmentno', models.TextField(blank=True, db_column='EquipmentNo', null=True)),
                ('unitno', models.CharField(blank=True, db_column='UnitNo', max_length=50, null=True)),
                ('partno', models.TextField(blank=True, db_column='PartNo', null=True)),
                ('pid', models.IntegerField(blank=True, db_column='PId', null=True)),
                ('cid', models.IntegerField(blank=True, db_column='CId', null=True)),
                ('itemid', models.IntegerField(blank=True, db_column='ItemId', null=True)),
                ('qty', models.FloatField(blank=True, db_column='Qty', null=True)),
            ],
            options={
                'db_table': 'tblDG_GUNRAIL_BOM_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgGunrailCrossrail',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('length', models.FloatField(blank=True, db_column='Length', null=True)),
                ('no', models.FloatField(blank=True, db_column='No', null=True)),
            ],
            options={
                'db_table': 'tblDG_Gunrail_CrossRail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgGunrailCrossrailDispatch',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('length', models.FloatField(blank=True, db_column='Length', null=True)),
                ('no', models.FloatField(blank=True, db_column='No', null=True)),
            ],
            options={
                'db_table': 'tblDG_Gunrail_CrossRail_Dispatch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgGunrailLongrail',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('length', models.FloatField(blank=True, db_column='Length', null=True)),
                ('no', models.FloatField(blank=True, db_column='No', null=True)),
            ],
            options={
                'db_table': 'tblDG_Gunrail_LongRail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgGunrailLongrailDispatch',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('length', models.FloatField(blank=True, db_column='Length', null=True)),
                ('no', models.FloatField(blank=True, db_column='No', null=True)),
            ],
            options={
                'db_table': 'tblDG_Gunrail_LongRail_Dispatch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgGunrailPitchDispatchMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(blank=True, db_column='SysDate', max_length=50, null=True)),
                ('systime', models.CharField(blank=True, db_column='SysTime', max_length=50, null=True)),
                ('compid', models.IntegerField(blank=True, db_column='CompId', null=True)),
                ('sessionid', models.CharField(blank=True, db_column='SessionId', max_length=50, null=True)),
                ('finyearid', models.IntegerField(blank=True, db_column='FinYearId', null=True)),
                ('wono', models.CharField(blank=True, db_column='WONo', max_length=50, null=True)),
                ('pitch', models.FloatField(blank=True, db_column='Pitch', null=True)),
                ('type', models.IntegerField(blank=True, db_column='Type', null=True)),
            ],
            options={
                'db_table': 'tblDG_Gunrail_Pitch_Dispatch_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgGunrailPitchMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(blank=True, db_column='SysDate', max_length=50, null=True)),
                ('systime', models.CharField(blank=True, db_column='SysTime', max_length=50, null=True)),
                ('compid', models.IntegerField(blank=True, db_column='CompId', null=True)),
                ('sessionid', models.CharField(blank=True, db_column='SessionId', max_length=50, null=True)),
                ('finyearid', models.IntegerField(blank=True, db_column='FinYearId', null=True)),
                ('wono', models.CharField(blank=True, db_column='WONo', max_length=50, null=True)),
                ('pitch', models.FloatField(blank=True, db_column='Pitch', null=True)),
                ('type', models.IntegerField(blank=True, db_column='Type', null=True)),
            ],
            options={
                'db_table': 'tblDG_Gunrail_Pitch_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgItemClass',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('class_field', models.TextField(blank=True, db_column='Class', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'tblDG_Item_Class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgItemMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(db_column='SysDate', max_length=50)),
                ('systime', models.CharField(db_column='SysTime', max_length=50)),
                ('compid', models.IntegerField(db_column='CompId')),
                ('finyearid', models.IntegerField(db_column='FinYearId')),
                ('sessionid', models.CharField(db_column='SessionId', max_length=50)),
                ('cid', models.IntegerField(blank=True, db_column='CId', null=True)),
                ('partno', models.TextField(blank=True, db_column='PartNo', null=True)),
                ('itemcode', models.TextField(blank=True, db_column='ItemCode', null=True)),
                ('manfdesc', models.TextField(blank=True, db_column='ManfDesc', null=True)),
                ('uombasic', models.IntegerField(blank=True, db_column='UOMBasic', null=True)),
                ('minorderqty', models.FloatField(blank=True, db_column='MinOrderQty', null=True)),
                ('minstockqty', models.FloatField(blank=True, db_column='MinStockQty', null=True)),
                ('stockqty', models.FloatField(db_column='StockQty')),
                ('process', models.IntegerField(blank=True, db_column='Process', null=True)),
                ('class_field', models.IntegerField(blank=True, db_column='Class', null=True)),
                ('leaddays', models.TextField(blank=True, db_column='LeadDays', null=True)),
                ('inspectiondays', models.TextField(blank=True, db_column='InspectionDays', null=True)),
                ('location', models.IntegerField(blank=True, db_column='Location', null=True)),
                ('filename', models.TextField(blank=True, db_column='FileName', null=True)),
                ('filesize', models.FloatField(blank=True, db_column='FileSize', null=True)),
                ('contenttype', models.TextField(blank=True, db_column='ContentType', null=True)),
                ('filedata', models.BinaryField(blank=True, db_column='FileData', null=True)),
                ('absolute', models.IntegerField(blank=True, db_column='Absolute', null=True)),
                ('openingbaldate', models.TextField(db_column='OpeningBalDate')),
                ('openingbalqty', models.FloatField(db_column='OpeningBalQty')),
                ('uomconfact', models.IntegerField(blank=True, db_column='UOMConFact', null=True)),
                ('excise', models.IntegerField(db_column='Excise')),
                ('importlocal', models.IntegerField(db_column='ImportLocal')),
                ('attname', models.TextField(blank=True, db_column='AttName', null=True)),
                ('attsize', models.FloatField(blank=True, db_column='AttSize', null=True)),
                ('attcontenttype', models.TextField(blank=True, db_column='AttContentType', null=True)),
                ('attdata', models.BinaryField(blank=True, db_column='AttData', null=True)),
                ('buyer', models.IntegerField(blank=True, db_column='Buyer', null=True)),
                ('ahid', models.IntegerField(blank=True, db_column='AHId', null=True)),
                ('hsncode', models.CharField(blank=True, db_column='HSNcode', max_length=10, null=True)),
            ],
            options={
                'db_table': 'tblDG_Item_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgLocationMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(blank=True, db_column='SysDate', max_length=50, null=True)),
                ('systime', models.CharField(blank=True, db_column='SysTime', max_length=50, null=True)),
                ('compid', models.IntegerField(blank=True, db_column='CompId', null=True)),
                ('finyearid', models.IntegerField(blank=True, db_column='FinYearId', null=True)),
                ('sessionid', models.TextField(blank=True, db_column='SessionId', null=True)),
                ('locationlabel', models.TextField(blank=True, db_column='LocationLabel', null=True)),
                ('locationno', models.TextField(blank=True, db_column='LocationNo', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'tblDG_Location_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbldgSubcategoryMaster',
            fields=[
                ('scid', models.AutoField(db_column='SCId', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(db_column='SysDate', max_length=50)),
                ('systime', models.CharField(db_column='SysTime', max_length=50)),
                ('compid', models.IntegerField(db_column='CompId')),
                ('finyearid', models.IntegerField(db_column='FinYearId')),
                ('sessionid', models.CharField(db_column='SessionId', max_length=50)),
                ('cid', models.IntegerField(db_column='CId')),
                ('scname', models.TextField(db_column='SCName')),
                ('symbol', models.TextField(db_column='Symbol')),
            ],
            options={
                'db_table': 'tblDG_SubCategory_Master',
                'managed': False,
            },
        ),
    ]
