"""
Comprehensive Tests for sys_admin Module
Generated by test-coverage-generator skill

Test Coverage:
- Models: Country, State, City, Company, FinancialYear, Unit, Tax masters
- Views: All CRUD operations with HTMX support
- Forms: Validation and custom clean methods
- Services: FinancialYearService business logic

Target Coverage: 85%+
"""

import pytest
from django.test import Client
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import datetime, timedelta, date
from django.core.exceptions import ValidationError

from .models import (
    Tblcountry, Tblstate, Tblcity, TblcompanyMaster,
    TblfinancialMaster, UnitMaster, TblexciseserMaster,
    TblvatMaster, TblgstMaster
)
from .forms import (
    CountryForm, StateForm, CityForm, FinancialYearForm,
    FinancialYearUpdateForm, UnitMasterForm
)
from .services import FinancialYearService


# ============================================================================
# FIXTURES
# ============================================================================

@pytest.fixture
def client():
    """Django test client."""
    return Client()


@pytest.fixture
def authenticated_user(db):
    """Create and return authenticated user."""
    user = User.objects.create_user(
        username='testuser',
        password='testpass123',
        email='test@example.com'
    )
    return user


@pytest.fixture
def authenticated_client(client, authenticated_user):
    """Return client logged in as authenticated_user."""
    client.login(username='testuser', password='testpass123')
    return client


@pytest.fixture
def sample_country(db):
    """Create sample country for testing."""
    return Tblcountry.objects.create(
        countryname='TestCountry',
        currency='USD',
        symbol='$',
        keyshortcut='TC'
    )


@pytest.fixture
def sample_state(db, sample_country):
    """Create sample state for testing."""
    return Tblstate.objects.create(
        statename='TestState',
        cid=sample_country
    )


@pytest.fixture
def sample_city(db, sample_state):
    """Create sample city for testing."""
    return Tblcity.objects.create(
        cityname='TestCity',
        sid=sample_state
    )


@pytest.fixture
def sample_company(db, sample_city):
    """Create sample company for testing."""
    return TblcompanyMaster.objects.create(
        sysdate='18-10-2025',
        systime='09:00:00',
        companyname='Test Company Ltd',
        regdstate=1,
        regdcountry=1,
        plantstate=1,
        plantcountry=1,
        plantcity=sample_city,
        regdcity=sample_city
    )


@pytest.fixture
def sample_financial_year(db, sample_company):
    """Create sample financial year for testing."""
    return TblfinancialMaster.objects.create(
        sysdate='18-10-2025',
        systime='09:00:00',
        sessionid='test-session',
        compid=sample_company.compid,
        finyear='2024-2025',
        finyearfrom='01-04-2024',
        finyearto='31-03-2025',
        flag=1
    )


@pytest.fixture
def sample_unit(db):
    """Create sample unit for testing."""
    return UnitMaster.objects.create(
        unitname='Kilogram',
        symbol='KG',
        effectoninvoice=1
    )


# ============================================================================
# MODEL TESTS
# ============================================================================

@pytest.mark.django_db
class TestCountryModel:
    """Test cases for Tblcountry model."""

    def test_country_creation(self):
        """Test creating a country instance."""
        country = Tblcountry.objects.create(
            countryname='India',
            currency='INR',
            symbol='₹',
            keyshortcut='IN'
        )
        assert country.pk is not None
        assert country.countryname == 'India'
        assert country.currency == 'INR'

    def test_country_str_method(self):
        """Test __str__ method returns country name."""
        country = Tblcountry.objects.create(countryname='USA')
        assert str(country) == 'USA'

    def test_country_str_method_fallback(self):
        """Test __str__ method with None countryname."""
        country = Tblcountry.objects.create(countryname=None)
        assert str(country) == f"Country {country.cid}"

    def test_country_managed_false(self):
        """Verify model uses managed=False."""
        assert Tblcountry._meta.managed is False

    def test_country_db_table(self):
        """Verify db_table is set correctly."""
        assert Tblcountry._meta.db_table == 'tblCountry'


@pytest.mark.django_db
class TestStateModel:
    """Test cases for Tblstate model."""

    def test_state_creation(self, sample_country):
        """Test creating a state instance."""
        state = Tblstate.objects.create(
            statename='Maharashtra',
            cid=sample_country
        )
        assert state.pk is not None
        assert state.statename == 'Maharashtra'
        assert state.cid == sample_country

    def test_state_foreign_key_relationship(self, sample_country):
        """Test ForeignKey relationship with Country."""
        state = Tblstate.objects.create(
            statename='Karnataka',
            cid=sample_country
        )
        assert state.cid.countryname == sample_country.countryname

    def test_state_str_method(self):
        """Test __str__ method returns state name."""
        state = Tblstate.objects.create(statename='Gujarat')
        assert str(state) == 'Gujarat'


@pytest.mark.django_db
class TestCityModel:
    """Test cases for Tblcity model."""

    def test_city_creation(self, sample_state):
        """Test creating a city instance."""
        city = Tblcity.objects.create(
            cityname='Mumbai',
            sid=sample_state
        )
        assert city.pk is not None
        assert city.cityname == 'Mumbai'
        assert city.sid == sample_state

    def test_city_foreign_key_relationship(self, sample_state):
        """Test ForeignKey relationship with State."""
        city = Tblcity.objects.create(
            cityname='Pune',
            sid=sample_state
        )
        assert city.sid.statename == sample_state.statename
        assert city.sid.cid.countryname == sample_state.cid.countryname


@pytest.mark.django_db
class TestFinancialYearModel:
    """Test cases for TblfinancialMaster model."""

    def test_financial_year_creation(self, sample_company):
        """Test creating a financial year instance."""
        fy = TblfinancialMaster.objects.create(
            sysdate='18-10-2025',
            systime='10:00:00',
            sessionid='session123',
            compid=sample_company.compid,
            finyear='2025-2026',
            finyearfrom='01-04-2025',
            finyearto='31-03-2026',
            flag=1
        )
        assert fy.pk is not None
        assert fy.finyear == '2025-2026'
        assert fy.flag == 1

    def test_financial_year_flag(self, sample_financial_year):
        """Test flag field for active/inactive status."""
        assert sample_financial_year.flag == 1
        sample_financial_year.flag = 0
        sample_financial_year.save()
        sample_financial_year.refresh_from_db()
        assert sample_financial_year.flag == 0


@pytest.mark.django_db
class TestUnitMaster:
    """Test cases for UnitMaster model."""

    def test_unit_creation(self):
        """Test creating a unit instance."""
        unit = UnitMaster.objects.create(
            unitname='Meter',
            symbol='M',
            effectoninvoice=1
        )
        assert unit.pk is not None
        assert unit.unitname == 'Meter'
        assert unit.symbol == 'M'

    def test_unit_str_method(self):
        """Test __str__ method returns symbol."""
        unit = UnitMaster.objects.create(
            unitname='Liter',
            symbol='L'
        )
        assert str(unit) == 'L'


# ============================================================================
# FORM TESTS
# ============================================================================

@pytest.mark.django_db
class TestCountryForm:
    """Test cases for CountryForm."""

    def test_valid_form(self):
        """Test form with valid data."""
        form_data = {
            'countryname': 'Germany',
            'currency': 'EUR',
            'symbol': '€',
            'keyshortcut': 'DE'
        }
        form = CountryForm(data=form_data)
        assert form.is_valid()

    def test_invalid_form_missing_required_field(self):
        """Test form validation fails when required field is missing."""
        form_data = {'countryname': 'France'}  # Missing currency, symbol
        form = CountryForm(data=form_data)
        assert not form.is_valid()
        assert 'currency' in form.errors or 'symbol' in form.errors

    def test_clean_countryname_empty(self):
        """Test countryname validation rejects empty strings."""
        form_data = {
            'countryname': '   ',  # Whitespace only
            'currency': 'USD',
            'symbol': '$'
        }
        form = CountryForm(data=form_data)
        assert not form.is_valid()
        assert 'countryname' in form.errors

    def test_clean_countryname_unique(self, sample_country):
        """Test countryname uniqueness validation."""
        form_data = {
            'countryname': sample_country.countryname,  # Duplicate
            'currency': 'USD',
            'symbol': '$'
        }
        form = CountryForm(data=form_data)
        assert not form.is_valid()
        assert 'countryname' in form.errors


@pytest.mark.django_db
class TestStateForm:
    """Test cases for StateForm."""

    def test_valid_form(self, sample_country):
        """Test form with valid data."""
        form_data = {
            'cid': sample_country.cid,
            'statename': 'TestStateName'
        }
        form = StateForm(data=form_data)
        assert form.is_valid()

    def test_invalid_form_missing_country(self):
        """Test form validation fails without country."""
        form_data = {'statename': 'TestState'}  # Missing cid
        form = StateForm(data=form_data)
        assert not form.is_valid()
        assert 'cid' in form.errors


@pytest.mark.django_db
class TestCityForm:
    """Test cases for CityForm."""

    def test_valid_form(self, sample_state):
        """Test form with valid data."""
        form_data = {
            'sid': sample_state.sid,
            'cityname': 'TestCityName'
        }
        form = CityForm(data=form_data)
        assert form.is_valid()

    def test_clean_cityname_empty(self):
        """Test cityname validation rejects empty strings."""
        form_data = {
            'cityname': '  ',  # Whitespace
            'sid': 1
        }
        form = CityForm(data=form_data)
        assert not form.is_valid()


@pytest.mark.django_db
class TestFinancialYearForm:
    """Test cases for FinancialYearForm."""

    def test_valid_form(self, sample_company):
        """Test form with valid data."""
        form_data = {
            'company': sample_company.compid,
            'finyear': '2025-2026',
            'finyearfrom': date(2025, 4, 1),
            'finyearto': date(2026, 3, 31)
        }
        form = FinancialYearForm(data=form_data)
        assert form.is_valid()

    def test_invalid_date_range(self, sample_company):
        """Test validation fails when end date is before start date."""
        form_data = {
            'company': sample_company.compid,
            'finyear': '2025-2026',
            'finyearfrom': date(2026, 3, 31),
            'finyearto': date(2025, 4, 1)  # Before start date!
        }
        form = FinancialYearForm(data=form_data)
        assert not form.is_valid()

    def test_invalid_date_range_too_short(self, sample_company):
        """Test validation fails when date range is too short."""
        form_data = {
            'company': sample_company.compid,
            'finyear': '2025-2026',
            'finyearfrom': date(2025, 4, 1),
            'finyearto': date(2025, 6, 1)  # Only 2 months!
        }
        form = FinancialYearForm(data=form_data)
        assert not form.is_valid()

    def test_duplicate_financial_year(self, sample_company, sample_financial_year):
        """Test validation fails for duplicate financial year."""
        form_data = {
            'company': sample_company.compid,
            'finyear': sample_financial_year.finyear,  # Duplicate!
            'finyearfrom': date(2024, 4, 1),
            'finyearto': date(2025, 3, 31)
        }
        form = FinancialYearForm(data=form_data)
        assert not form.is_valid()


@pytest.mark.django_db
class TestUnitMasterForm:
    """Test cases for UnitMasterForm."""

    def test_valid_form(self):
        """Test form with valid data."""
        form_data = {
            'unitname': 'Pieces',
            'symbol': 'PCS',
            'effectoninvoice': True
        }
        form = UnitMasterForm(data=form_data)
        assert form.is_valid()

    def test_clean_unitname_empty(self):
        """Test unitname validation rejects empty strings."""
        form_data = {
            'unitname': '  ',
            'symbol': 'X'
        }
        form = UnitMasterForm(data=form_data)
        assert not form.is_valid()
        assert 'unitname' in form.errors


# ============================================================================
# VIEW TESTS - COUNTRY
# ============================================================================

@pytest.mark.django_db
class TestCountryListView:
    """Test cases for CountryListView."""

    def test_list_view_requires_authentication(self, client):
        """Test unauthenticated access redirects to login."""
        url = reverse('sys_admin:country-list')
        response = client.get(url)
        assert response.status_code == 302  # Redirect
        assert '/login/' in response.url or 'login' in response.url

    def test_list_view_authenticated(self, authenticated_client, sample_country):
        """Test authenticated user can access list view."""
        url = reverse('sys_admin:country-list')
        response = authenticated_client.get(url)
        assert response.status_code == 200
        assert sample_country.countryname in str(response.content)

    def test_list_view_search(self, authenticated_client, sample_country):
        """Test search functionality."""
        url = reverse('sys_admin:country-list')
        response = authenticated_client.get(url, {'search': sample_country.countryname})
        assert response.status_code == 200
        assert sample_country.countryname in str(response.content)

    def test_list_view_htmx_request_returns_partial(self, authenticated_client):
        """Test HTMX request returns partial template."""
        url = reverse('sys_admin:country-list')
        response = authenticated_client.get(url, HTTP_HX_REQUEST='true')
        assert response.status_code == 200
        assert 'partials/' in response.template_name[0]


@pytest.mark.django_db
class TestCountryCreateView:
    """Test cases for CountryCreateView."""

    def test_create_view_post_valid(self, authenticated_client):
        """Test POST with valid data creates country."""
        url = reverse('sys_admin:country-create')
        data = {
            'countryname': 'NewCountry',
            'currency': 'XXX',
            'symbol': 'X'
        }
        response = authenticated_client.post(url, data)
        assert response.status_code in [200, 302]
        assert Tblcountry.objects.filter(countryname='NewCountry').exists()

    def test_create_view_post_invalid(self, authenticated_client):
        """Test POST with invalid data shows errors."""
        url = reverse('sys_admin:country-create')
        data = {'countryname': ''}  # Invalid: empty
        response = authenticated_client.post(url, data)
        assert not Tblcountry.objects.filter(countryname='').exists()


@pytest.mark.django_db
class TestCountryUpdateView:
    """Test cases for CountryUpdateView."""

    def test_update_view_get(self, authenticated_client, sample_country):
        """Test GET request shows edit form."""
        url = reverse('sys_admin:country-edit', kwargs={'cid': sample_country.cid})
        response = authenticated_client.get(url)
        assert response.status_code == 200

    def test_update_view_post_valid(self, authenticated_client, sample_country):
        """Test POST with valid data updates country."""
        url = reverse('sys_admin:country-edit', kwargs={'cid': sample_country.cid})
        data = {
            'countryname': 'UpdatedCountry',
            'currency': 'UPD',
            'symbol': 'U'
        }
        response = authenticated_client.post(url, data)
        sample_country.refresh_from_db()
        assert sample_country.countryname == 'UpdatedCountry'


@pytest.mark.django_db
class TestCountryDeleteView:
    """Test cases for CountryDeleteView."""

    def test_delete_view(self, authenticated_client, sample_country):
        """Test DELETE request removes country."""
        cid = sample_country.cid
        url = reverse('sys_admin:country-delete', kwargs={'cid': cid})
        response = authenticated_client.delete(url)
        assert response.status_code in [200, 204, 302]
        assert not Tblcountry.objects.filter(cid=cid).exists()


# ============================================================================
# VIEW TESTS - STATE
# ============================================================================

@pytest.mark.django_db
class TestStateViews:
    """Test cases for State CRUD views."""

    def test_state_list_view_authenticated(self, authenticated_client, sample_state):
        """Test authenticated access to state list."""
        url = reverse('sys_admin:state-list')
        response = authenticated_client.get(url)
        assert response.status_code == 200
        assert sample_state.statename in str(response.content)

    def test_state_create_view(self, authenticated_client, sample_country):
        """Test creating a new state."""
        url = reverse('sys_admin:state-create')
        data = {
            'cid': sample_country.cid,
            'statename': 'NewState'
        }
        response = authenticated_client.post(url, data)
        assert Tblstate.objects.filter(statename='NewState').exists()

    def test_state_update_view(self, authenticated_client, sample_state):
        """Test updating an existing state."""
        url = reverse('sys_admin:state-edit', kwargs={'sid': sample_state.sid})
        data = {
            'cid': sample_state.cid.cid,
            'statename': 'UpdatedState'
        }
        response = authenticated_client.post(url, data)
        sample_state.refresh_from_db()
        assert sample_state.statename == 'UpdatedState'


# ============================================================================
# VIEW TESTS - CITY
# ============================================================================

@pytest.mark.django_db
class TestCityViews:
    """Test cases for City CRUD views."""

    def test_city_list_view_authenticated(self, authenticated_client, sample_city):
        """Test authenticated access to city list."""
        url = reverse('sys_admin:city-list')
        response = authenticated_client.get(url)
        assert response.status_code == 200
        assert sample_city.cityname in str(response.content)

    def test_city_create_view(self, authenticated_client, sample_state):
        """Test creating a new city."""
        url = reverse('sys_admin:city-create')
        data = {
            'sid': sample_state.sid,
            'cityname': 'NewCity'
        }
        response = authenticated_client.post(url, data)
        assert Tblcity.objects.filter(cityname='NewCity').exists()


# ============================================================================
# VIEW TESTS - FINANCIAL YEAR
# ============================================================================

@pytest.mark.django_db
class TestFinancialYearViews:
    """Test cases for Financial Year CRUD views."""

    def test_financial_year_list_view(self, authenticated_client, sample_financial_year):
        """Test financial year list view."""
        url = reverse('sys_admin:financial-year-list')
        response = authenticated_client.get(url)
        assert response.status_code == 200

    def test_financial_year_create_view(self, authenticated_client, sample_company):
        """Test financial year create redirects to confirmation."""
        url = reverse('sys_admin:financial-year-create')
        data = {
            'company': sample_company.compid,
            'finyear': '2026-2027',
            'finyearfrom': '2026-04-01',
            'finyearto': '2027-03-31'
        }
        response = authenticated_client.post(url, data)
        assert response.status_code == 302  # Redirects to confirmation

    def test_financial_year_confirm_view(self, authenticated_client, sample_company):
        """Test financial year confirmation page."""
        # Set pending FY in session
        session = authenticated_client.session
        session['pending_financial_year'] = {
            'compid': sample_company.compid,
            'company_name': sample_company.companyname,
            'finyear': '2026-2027',
            'finyearfrom': '01-04-2026',
            'finyearto': '31-03-2027'
        }
        session.save()

        url = reverse('sys_admin:financial-year-confirm')
        response = authenticated_client.get(url)
        assert response.status_code == 200

    def test_financial_year_delete_soft_delete(self, authenticated_client, sample_financial_year):
        """Test delete sets flag=0 instead of removing object."""
        url = reverse('sys_admin:financial-year-delete', kwargs={'finyearid': sample_financial_year.finyearid})
        response = authenticated_client.delete(url)
        sample_financial_year.refresh_from_db()
        assert sample_financial_year.flag == 0  # Soft deleted
        assert TblfinancialMaster.objects.filter(finyearid=sample_financial_year.finyearid).exists()


# ============================================================================
# VIEW TESTS - UNIT MASTER
# ============================================================================

@pytest.mark.django_db
class TestUnitMasterViews:
    """Test cases for Unit Master CRUD views."""

    def test_unit_list_view(self, authenticated_client, sample_unit):
        """Test unit master list view."""
        url = reverse('sys_admin:unit-master-list')
        response = authenticated_client.get(url)
        assert response.status_code == 200

    def test_unit_create_view(self, authenticated_client):
        """Test creating a new unit."""
        url = reverse('sys_admin:unit-master-create')
        data = {
            'unitname': 'Dozen',
            'symbol': 'DZN',
            'effectoninvoice': True
        }
        response = authenticated_client.post(url, data)
        assert UnitMaster.objects.filter(unitname='Dozen').exists()


# ============================================================================
# SERVICE TESTS
# ============================================================================

@pytest.mark.django_db
class TestFinancialYearService:
    """Test cases for FinancialYearService."""

    def test_create_financial_year(self, sample_company):
        """Test creating financial year via service."""
        fy = FinancialYearService.create_financial_year(
            compid=sample_company.compid,
            finyear='2027-2028',
            finyearfrom='01-04-2027',
            finyearto='31-03-2028',
            sessionid='test-session-123'
        )
        assert fy.pk is not None
        assert fy.finyear == '2027-2028'
        assert fy.flag == 1

    def test_get_financial_year_with_company(self, sample_financial_year, sample_company):
        """Test retrieving financial year with company details."""
        result = FinancialYearService.get_financial_year_with_company(
            sample_financial_year.finyearid
        )
        assert result['financial_year'] == sample_financial_year
        assert result['company'].compid == sample_company.compid

    def test_get_active_financial_years_by_company(self, sample_financial_year, sample_company):
        """Test getting all active financial years for a company."""
        # Create another active FY
        TblfinancialMaster.objects.create(
            sysdate='18-10-2025',
            systime='10:00:00',
            sessionid='test',
            compid=sample_company.compid,
            finyear='2025-2026',
            finyearfrom='01-04-2025',
            finyearto='31-03-2026',
            flag=1
        )

        active_fys = FinancialYearService.get_active_financial_years_by_company(
            sample_company.compid
        )
        assert active_fys.count() >= 2


# ============================================================================
# INTEGRATION TESTS
# ============================================================================

@pytest.mark.django_db
class TestCountryCRUDWorkflow:
    """End-to-end workflow test for Country CRUD."""

    def test_complete_country_crud_workflow(self, authenticated_client):
        """Test create → read → update → delete workflow for Country."""
        # Step 1: Create
        create_url = reverse('sys_admin:country-create')
        data = {'countryname': 'WorkflowCountry', 'currency': 'WFC', 'symbol': 'W'}
        response = authenticated_client.post(create_url, data)
        assert response.status_code in [200, 302]

        # Step 2: Read (List)
        country = Tblcountry.objects.get(countryname='WorkflowCountry')
        list_url = reverse('sys_admin:country-list')
        response = authenticated_client.get(list_url)
        assert 'WorkflowCountry' in str(response.content)

        # Step 3: Update
        update_url = reverse('sys_admin:country-edit', kwargs={'cid': country.cid})
        data = {'countryname': 'UpdatedWorkflow', 'currency': 'UWF', 'symbol': 'U'}
        response = authenticated_client.post(update_url, data)
        country.refresh_from_db()
        assert country.countryname == 'UpdatedWorkflow'

        # Step 4: Delete
        delete_url = reverse('sys_admin:country-delete', kwargs={'cid': country.cid})
        response = authenticated_client.delete(delete_url)
        assert not Tblcountry.objects.filter(cid=country.cid).exists()


@pytest.mark.django_db
class TestHierarchicalMasterData:
    """Test hierarchical relationships: Country → State → City."""

    def test_cascading_data_entry(self, authenticated_client):
        """Test creating hierarchical master data."""
        # Create Country
        country = Tblcountry.objects.create(
            countryname='TestHierarchy',
            currency='THC',
            symbol='T'
        )

        # Create State
        state = Tblstate.objects.create(
            statename='TestHierarchyState',
            cid=country
        )

        # Create City
        city = Tblcity.objects.create(
            cityname='TestHierarchyCity',
            sid=state
        )

        # Verify relationships
        assert city.sid == state
        assert state.cid == country
        assert city.sid.cid == country
