using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Web;
using System.Web.SessionState;
using System.Web.UI;
using System.Web.UI.WebControls;
using ASP;

public class Module_Inventory_Reports_SearchViewFieldMRS : Page, IRequiresSessionState
{
	protected CheckBox checkAll;

	protected Label lblMRS;

	protected CheckBoxList chkFields;

	protected Panel Panel2;

	protected Label lblMIN;

	protected CheckBoxList chkFields3;

	protected Panel Panel3;

	protected Button btnSub;

	protected Button btnExport;

	protected Button btnCancel;

	protected GridView GridView1;

	protected Panel Panel1;

	private clsFunctions fun = new clsFunctions();

	private string _connStr = ConfigurationManager.ConnectionStrings["LocalSqlServer"].ConnectionString;

	private int flag;

	private int CompId;

	private string FirstCond = string.Empty;

	private string EmpId = string.Empty;

	private string Itemcode = string.Empty;

	private string ICategory = string.Empty;

	private string BGGroup = string.Empty;

	private string WONo = string.Empty;

	private string FromDate = string.Empty;

	private string ToDate = string.Empty;

	private string StrDate = string.Empty;

	private string POCompletePending = string.Empty;

	protected ProfileCommon Profile => (ProfileCommon)Context.Profile;

	protected global_asax ApplicationInstance => (global_asax)Context.ApplicationInstance;

	protected void Page_Load(object sender, EventArgs e)
	{
		try
		{
			CompId = Convert.ToInt32(Session["compid"]);
			if (!string.IsNullOrEmpty(base.Request.QueryString["MRSType"]) && !string.IsNullOrEmpty(base.Request.QueryString["MRSno"]))
			{
				switch (Convert.ToInt32(base.Request.QueryString["MRSType"]))
				{
				case 1:
					FirstCond = " And MRSNo='" + base.Request.QueryString["MRSno"].ToString() + "' ";
					break;
				case 2:
					FirstCond = " And MINNo='" + base.Request.QueryString["MRSno"].ToString() + "'";
					break;
				case 3:
					FirstCond = " ";
					break;
				}
			}
			if (!string.IsNullOrEmpty(base.Request.QueryString["ICode"]))
			{
				Itemcode = " And ItemCode='" + base.Request.QueryString["ICode"].ToString() + "'";
			}
			if (!string.IsNullOrEmpty(base.Request.QueryString["ICategory"]))
			{
				ICategory = " And CId='" + base.Request.QueryString["ICategory"].ToString() + "'";
			}
			if (!string.IsNullOrEmpty(base.Request.QueryString["MRSType"]))
			{
				flag = Convert.ToInt32(base.Request.QueryString["MRSType"]);
			}
			if (!string.IsNullOrEmpty(base.Request.QueryString["FDateMRS"]) && !string.IsNullOrEmpty(base.Request.QueryString["TDateMRS"]))
			{
				FromDate = fun.FromDate(base.Request.QueryString["FDateMRS"]);
				ToDate = fun.FromDate(base.Request.QueryString["TDateMRS"]);
				switch (Convert.ToInt32(base.Request.QueryString["Rbtn"]))
				{
				case 1:
					StrDate = " And MRSDate between '" + FromDate + "' And '" + ToDate + "'";
					break;
				case 2:
					StrDate = " And MINDate between '" + FromDate + "' And '" + ToDate + "'";
					break;
				}
			}
			if (!string.IsNullOrEmpty(base.Request.QueryString["EmpidMRS"]))
			{
				EmpId = " And EmpId='" + base.Request.QueryString["EmpidMRS"].ToString() + "'";
			}
			if (!string.IsNullOrEmpty(base.Request.QueryString["BGGroupMRS"]))
			{
				BGGroup = " And BGId='" + base.Request.QueryString["BGGroupMRS"].ToString() + "'";
			}
			if (!string.IsNullOrEmpty(base.Request.QueryString["WONoMRS"]))
			{
				WONo = " And WONo='" + base.Request.QueryString["WONoMRS"].ToString() + "'";
			}
			if (!base.IsPostBack)
			{
				BindTableColumns();
			}
			if (flag == 1 || flag == 3)
			{
				lblMRS.Text = "MRS";
				lblMIN.Text = "MIN";
				chkFields.Items[0].Selected = true;
				chkFields.Items[1].Selected = true;
				chkFields.Items[2].Selected = true;
				chkFields.Items[3].Selected = true;
				chkFields.Items[11].Attributes.Add("style", "display:none;");
				chkFields.Items[12].Attributes.Add("style", "display:none;");
				chkFields.Items[13].Attributes.Add("style", "display:none;");
				chkFields.Items[14].Attributes.Add("style", "display:none;");
				chkFields.Items[15].Attributes.Add("style", "display:none;");
				chkFields.Items[16].Attributes.Add("style", "display:none;");
				chkFields.Items[17].Attributes.Add("style", "display:none;");
				chkFields.Items[0].Text = "Sr No";
				chkFields.Items[1].Text = "Item Code";
				chkFields.Items[4].Text = "Date";
				chkFields.Items[5].Text = "MRS No";
				chkFields.Items[6].Text = "BG Group";
				chkFields.Items[7].Text = "WO No";
				chkFields.Items[8].Text = "Req Qty";
				chkFields.Items[9].Text = "Remarks";
				chkFields.Items[10].Text = "Generated By";
				chkFields3.Items[0].Text = "Date";
				chkFields3.Items[1].Text = "MIN No";
				chkFields3.Items[2].Text = "Issue Qty";
				chkFields3.Items[3].Text = "Generated By";
			}
			if (flag == 2)
			{
				lblMRS.Text = "MIN";
				lblMIN.Text = "MRS";
				chkFields.Items[0].Selected = true;
				chkFields.Items[1].Selected = true;
				chkFields.Items[2].Selected = true;
				chkFields.Items[3].Selected = true;
				chkFields.Items[0].Text = "Sr No";
				chkFields.Items[1].Text = "Item Code";
				chkFields.Items[4].Text = "Date";
				chkFields.Items[5].Text = "MIN No";
				chkFields.Items[6].Text = "Issue Qty";
				chkFields.Items[7].Text = "Generated By";
				chkFields.Items[8].Attributes.Add("style", "display:none;");
				chkFields.Items[9].Attributes.Add("style", "display:none;");
				chkFields.Items[10].Attributes.Add("style", "display:none;");
				chkFields.Items[11].Attributes.Add("style", "display:none;");
				chkFields.Items[12].Attributes.Add("style", "display:none;");
				chkFields.Items[13].Attributes.Add("style", "display:none;");
				chkFields.Items[14].Attributes.Add("style", "display:none;");
				chkFields.Items[15].Attributes.Add("style", "display:none;");
				chkFields.Items[16].Attributes.Add("style", "display:none;");
				chkFields.Items[17].Attributes.Add("style", "display:none;");
				chkFields3.Items[0].Text = "Date";
				chkFields3.Items[1].Text = "MRS No";
				chkFields3.Items[2].Text = "WO No";
				chkFields3.Items[3].Text = "BG Group";
				chkFields3.Items[4].Text = "Req Qty";
				chkFields3.Items[5].Text = "Remarks";
				chkFields3.Items[6].Text = "Generated By";
				chkFields3.Items[7].Attributes.Add("style", "display:none;");
				chkFields3.Items[8].Attributes.Add("style", "display:none;");
				chkFields3.Items[9].Attributes.Add("style", "display:none;");
			}
		}
		catch (Exception)
		{
		}
	}

	protected void ShowGrid(object sender, EventArgs e)
	{
		try
		{
			int num = 0;
			if (flag == 1 || flag == 3)
			{
				foreach (ListItem item in chkFields.Items)
				{
					if (item.Selected)
					{
						BoundField boundField = new BoundField();
						boundField.DataField = item.Value;
						boundField.HeaderText = item.Text;
						GridView1.Columns.Add(boundField);
						num++;
					}
				}
				foreach (ListItem item2 in chkFields3.Items)
				{
					if (item2.Selected)
					{
						BoundField boundField2 = new BoundField();
						boundField2.DataField = item2.Value;
						boundField2.HeaderText = item2.Text;
						GridView1.Columns.Add(boundField2);
						num++;
					}
				}
				if (num > 0)
				{
					GetData();
				}
			}
			if (flag != 2)
			{
				return;
			}
			foreach (ListItem item3 in chkFields.Items)
			{
				if (item3.Selected)
				{
					BoundField boundField3 = new BoundField();
					boundField3.DataField = item3.Value;
					boundField3.HeaderText = item3.Text;
					GridView1.Columns.Add(boundField3);
					num++;
				}
			}
			foreach (ListItem item4 in chkFields3.Items)
			{
				if (item4.Selected)
				{
					BoundField boundField4 = new BoundField();
					boundField4.DataField = item4.Value;
					boundField4.HeaderText = item4.Text;
					GridView1.Columns.Add(boundField4);
					num++;
				}
			}
			if (num > 0)
			{
				GetData();
			}
		}
		catch (Exception)
		{
		}
	}

	private void BindTableColumns()
	{
		try
		{
			DataTable dataTable = new DataTable();
			DataTable dataTable2 = new DataTable();
			using SqlConnection connection = new SqlConnection(_connStr);
			if (flag == 1 || flag == 3)
			{
				using (SqlCommand sqlCommand = new SqlCommand("sp_columns", connection))
				{
					sqlCommand.CommandType = CommandType.StoredProcedure;
					sqlCommand.Parameters.AddWithValue("@table_name", "View_MRS_Item");
					using SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
					sqlDataAdapter.Fill(dataTable);
				}
				if (dataTable.Rows.Count > 0)
				{
					dataTable.Rows.RemoveAt(18);
					dataTable.AcceptChanges();
					chkFields.DataSource = dataTable;
					chkFields.DataBind();
				}
				using (SqlCommand sqlCommand2 = new SqlCommand("sp_columns", connection))
				{
					sqlCommand2.CommandType = CommandType.StoredProcedure;
					sqlCommand2.Parameters.AddWithValue("@table_name", "View_MRS_Item");
					using SqlDataAdapter sqlDataAdapter2 = new SqlDataAdapter(sqlCommand2);
					sqlDataAdapter2.Fill(dataTable2);
				}
				if (dataTable2.Rows.Count > 0)
				{
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(0);
					dataTable2.Rows.RemoveAt(4);
					chkFields3.DataSource = dataTable2;
					chkFields3.DataBind();
				}
			}
			if (flag != 2)
			{
				return;
			}
			using (SqlCommand sqlCommand3 = new SqlCommand("sp_columns", connection))
			{
				sqlCommand3.CommandType = CommandType.StoredProcedure;
				sqlCommand3.Parameters.AddWithValue("@table_name", "View_MIN_Item");
				using SqlDataAdapter sqlDataAdapter3 = new SqlDataAdapter(sqlCommand3);
				sqlDataAdapter3.Fill(dataTable);
			}
			if (dataTable.Rows.Count > 0)
			{
				chkFields.DataSource = dataTable;
				chkFields.DataBind();
			}
			using (SqlCommand sqlCommand4 = new SqlCommand("sp_columns", connection))
			{
				sqlCommand4.CommandType = CommandType.StoredProcedure;
				sqlCommand4.Parameters.AddWithValue("@table_name", "View_MIN_Item");
				using SqlDataAdapter sqlDataAdapter4 = new SqlDataAdapter(sqlCommand4);
				sqlDataAdapter4.Fill(dataTable2);
			}
			if (dataTable2.Rows.Count > 0)
			{
				dataTable2.Rows.RemoveAt(0);
				dataTable2.Rows.RemoveAt(0);
				dataTable2.Rows.RemoveAt(0);
				dataTable2.Rows.RemoveAt(0);
				dataTable2.Rows.RemoveAt(0);
				dataTable2.Rows.RemoveAt(0);
				dataTable2.Rows.RemoveAt(0);
				dataTable2.Rows.RemoveAt(0);
				chkFields3.DataSource = dataTable2;
				chkFields3.DataBind();
			}
		}
		catch (Exception)
		{
		}
	}

	private void GetData()
	{
		try
		{
			DataTable dataTable = new DataTable();
			using (SqlConnection connection = new SqlConnection(_connStr))
			{
				string cmdText = "";
				if (flag == 1 || flag == 3)
				{
					string text = string.Empty;
					if (chkFields.Items[0].Selected)
					{
						text = "ROW_NUMBER() OVER (ORDER BY ItemCode) AS SrNo";
					}
					if (chkFields.Items[1].Selected)
					{
						text += ",ItemCode";
					}
					if (chkFields.Items[2].Selected)
					{
						text += ",Description";
					}
					if (chkFields.Items[3].Selected)
					{
						text += ",UOM";
					}
					if (chkFields.Items[4].Selected)
					{
						text += ",REPLACE(CONVERT(varchar,CONVERT(datetime, SUBSTRING(MRSDate, CHARINDEX('-', MRSDate) + 1, 2) + '-' + LEFT(MRSDate, CHARINDEX('-', MRSDate) - 1) + '-' + RIGHT(MRSDate, CHARINDEX('-',REVERSE(MRSDate)) - 1)), 103), '/', '-') AS MRSDate";
					}
					if (chkFields.Items[5].Selected)
					{
						text += ",MRSNo";
					}
					if (chkFields.Items[6].Selected)
					{
						text += ",BGGroup";
					}
					if (chkFields.Items[7].Selected)
					{
						text += ",WONo";
					}
					if (chkFields.Items[8].Selected)
					{
						text += ",ReqQty";
					}
					if (chkFields.Items[9].Selected)
					{
						text += ",Remarks";
					}
					if (chkFields.Items[10].Selected)
					{
						text += ",GenBy";
					}
					if (chkFields3.Items[0].Selected)
					{
						text += ",REPLACE(CONVERT(varchar,CONVERT(datetime, SUBSTRING(MINDate, CHARINDEX('-', MINDate) + 1, 2) + '-' + LEFT(MINDate, CHARINDEX('-', MINDate) - 1) + '-' + RIGHT(MINDate, CHARINDEX('-',REVERSE(MINDate)) - 1)), 103), '/', '-') AS MINDate";
					}
					if (chkFields3.Items[0].Selected)
					{
						text += ",MINNo";
					}
					if (chkFields3.Items[2].Selected)
					{
						text += ",MINQty";
					}
					if (chkFields3.Items[3].Selected)
					{
						text += ",GenBy2";
					}
					cmdText = "SELECT " + text + " FROM View_MRS_Item where CompId='" + CompId + "'" + FirstCond + Itemcode + EmpId + WONo + BGGroup + StrDate + ICategory;
				}
				if (flag == 2)
				{
					string text2 = string.Empty;
					if (chkFields.Items[0].Selected)
					{
						text2 = "ROW_NUMBER() OVER (ORDER BY ItemCode) AS SrNo";
					}
					if (chkFields.Items[1].Selected)
					{
						text2 += ",ItemCode";
					}
					if (chkFields.Items[2].Selected)
					{
						text2 += ",Description";
					}
					if (chkFields.Items[3].Selected)
					{
						text2 += ",UOM";
					}
					if (chkFields.Items[4].Selected)
					{
						text2 += ",REPLACE(CONVERT(varchar,CONVERT(datetime, SUBSTRING(MINDate, CHARINDEX('-', MINDate) + 1, 2) + '-' + LEFT(MINDate, CHARINDEX('-', MINDate) - 1) + '-' + RIGHT(MINDate, CHARINDEX('-',REVERSE(MINDate)) - 1)), 103), '/', '-') AS MINDate";
					}
					if (chkFields.Items[5].Selected)
					{
						text2 += ",MINNo";
					}
					if (chkFields.Items[6].Selected)
					{
						text2 += ",IssueQty";
					}
					if (chkFields.Items[7].Selected)
					{
						text2 += ",EmpName";
					}
					if (chkFields3.Items[0].Selected)
					{
						text2 += ",REPLACE(CONVERT(varchar,CONVERT(datetime, SUBSTRING(MRSDate, CHARINDEX('-', MRSDate) + 1, 2) + '-' + LEFT(MRSDate, CHARINDEX('-', MRSDate) - 1) + '-' + RIGHT(MRSDate, CHARINDEX('-',REVERSE(MRSDate)) - 1)), 103), '/', '-') AS MRSDate";
					}
					if (chkFields3.Items[1].Selected)
					{
						text2 += ",MRSNo";
					}
					if (chkFields3.Items[2].Selected)
					{
						text2 += ",WONo";
					}
					if (chkFields3.Items[3].Selected)
					{
						text2 += ",BGGroup";
					}
					if (chkFields3.Items[4].Selected)
					{
						text2 += ",ReqQty";
					}
					if (chkFields3.Items[5].Selected)
					{
						text2 += ",Remarks";
					}
					if (chkFields3.Items[6].Selected)
					{
						text2 += ",EmpName2";
					}
					cmdText = "SELECT " + text2 + " FROM View_MIN_Item where CompId='" + CompId + "'" + FirstCond + Itemcode + EmpId + WONo + BGGroup + StrDate;
				}
				using SqlCommand selectCommand = new SqlCommand(cmdText, connection);
				using SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(selectCommand);
				sqlDataAdapter.Fill(dataTable);
			}
			if (dataTable.Rows.Count > 0)
			{
				GridView1.DataSource = dataTable;
				GridView1.DataBind();
				ViewState["dtList"] = dataTable;
			}
			else
			{
				string empty = string.Empty;
				empty = "No Records to Dispaly.";
				base.ClientScript.RegisterStartupScript(GetType(), "myalert", "alert('" + empty + "');", addScriptTags: true);
			}
		}
		catch (Exception)
		{
		}
	}

	protected void checkAll_CheckedChanged(object sender, EventArgs e)
	{
		try
		{
			if (flag == 1 || flag == 3)
			{
				if (checkAll.Checked)
				{
					foreach (ListItem item in chkFields.Items)
					{
						if (item.Value != "CompId" && item.Value != "BGId" && item.Value != "EmpId" && item.Value != "MINDate" && item.Value != "MINNo" && item.Value != "MINQty" && item.Value != "GenBy2")
						{
							item.Selected = true;
						}
					}
					foreach (ListItem item2 in chkFields3.Items)
					{
						if (item2.Value != "CompId" && item2.Value != "BGId" && item2.Value != "EmpId")
						{
							item2.Selected = true;
						}
					}
				}
				else
				{
					foreach (ListItem item3 in chkFields.Items)
					{
						item3.Selected = false;
					}
					foreach (ListItem item4 in chkFields3.Items)
					{
						item4.Selected = false;
					}
				}
			}
			if (flag != 2)
			{
				return;
			}
			if (checkAll.Checked)
			{
				foreach (ListItem item5 in chkFields.Items)
				{
					if (item5.Value != "CompId" && item5.Value != "BGId" && item5.Value != "EmpId" && item5.Value != "MRSDate" && item5.Value != "MRSNo" && item5.Value != "WONo" && item5.Value != "BGGroup" && item5.Value != "ReqQty" && item5.Value != "Remarks" && item5.Value != "EmpName2")
					{
						item5.Selected = true;
					}
				}
				{
					foreach (ListItem item6 in chkFields3.Items)
					{
						if (item6.Value != "CompId" && item6.Value != "BGId" && item6.Value != "EmpId")
						{
							item6.Selected = true;
						}
					}
					return;
				}
			}
			foreach (ListItem item7 in chkFields.Items)
			{
				item7.Selected = false;
			}
			foreach (ListItem item8 in chkFields3.Items)
			{
				item8.Selected = false;
			}
		}
		catch (Exception)
		{
		}
	}

	protected void btnExport_Click(object sender, EventArgs e)
	{
		try
		{
			DataTable dataTable = (DataTable)ViewState["dtList"];
			if (flag == 1 || flag == 3)
			{
				if (chkFields.Items[0].Selected)
				{
					dataTable.Columns["SrNo"].ColumnName = "Sr No";
				}
				if (chkFields.Items[1].Selected)
				{
					dataTable.Columns["ItemCode"].ColumnName = "Item Code";
				}
				if (chkFields.Items[4].Selected)
				{
					dataTable.Columns["MRSDate"].ColumnName = "Date";
				}
				if (chkFields.Items[5].Selected)
				{
					dataTable.Columns["MRSNo"].ColumnName = "MRS No";
				}
				if (chkFields.Items[6].Selected)
				{
					dataTable.Columns["BGGroup"].ColumnName = "BG Group";
				}
				if (chkFields.Items[8].Selected)
				{
					dataTable.Columns["ReqQty"].ColumnName = "Req Qty";
				}
				if (chkFields.Items[10].Selected)
				{
					dataTable.Columns["GenBy"].ColumnName = "Generated By";
				}
				if (chkFields3.Items[0].Selected)
				{
					dataTable.Columns["MINDate"].ColumnName = "MIN Date";
				}
				if (chkFields3.Items[1].Selected)
				{
					dataTable.Columns["MINNo"].ColumnName = "MIN No";
				}
				if (chkFields3.Items[2].Selected)
				{
					dataTable.Columns["MINQty"].ColumnName = "Issue Qty";
				}
				if (chkFields3.Items[3].Selected)
				{
					dataTable.Columns["GenBy2"].ColumnName = "MIN Generated By";
				}
			}
			else if (flag == 2)
			{
				if (chkFields.Items[0].Selected)
				{
					dataTable.Columns["SrNo"].ColumnName = "Sr No";
				}
				if (chkFields.Items[1].Selected)
				{
					dataTable.Columns["ItemCode"].ColumnName = "Item Code";
				}
				if (chkFields.Items[4].Selected)
				{
					dataTable.Columns["MINDate"].ColumnName = "Date";
				}
				if (chkFields.Items[5].Selected)
				{
					dataTable.Columns["MINNo"].ColumnName = "MIN No";
				}
				if (chkFields.Items[6].Selected)
				{
					dataTable.Columns["IssueQty"].ColumnName = "Issue Qty";
				}
				if (chkFields.Items[7].Selected)
				{
					dataTable.Columns["EmpName"].ColumnName = "Generated By";
				}
				if (chkFields3.Items[0].Selected)
				{
					dataTable.Columns["MRSNo"].ColumnName = "MRS No";
				}
				if (chkFields3.Items[1].Selected)
				{
					dataTable.Columns["MRSDate"].ColumnName = "MRS Date";
				}
				if (chkFields3.Items[2].Selected)
				{
					dataTable.Columns["BGGroup"].ColumnName = "BG Group";
				}
				if (chkFields3.Items[3].Selected)
				{
					dataTable.Columns["WONo"].ColumnName = "WO No";
				}
				if (chkFields3.Items[4].Selected)
				{
					dataTable.Columns["ReqQty"].ColumnName = "Req Qty";
				}
				if (chkFields3.Items[5].Selected)
				{
					dataTable.Columns["EmpName2"].ColumnName = "MRS Generated By";
				}
			}
			if (dataTable == null)
			{
				throw new Exception("No Records to Export");
			}
			string text = "D:\\ImportExcelFromDatabase\\myexcelfile_" + DateTime.Now.Day + "_" + DateTime.Now.Month + ".xls";
			FileInfo fileInfo = new FileInfo(text);
			StringWriter stringWriter = new StringWriter();
			HtmlTextWriter writer = new HtmlTextWriter(stringWriter);
			DataGrid dataGrid = new DataGrid();
			dataGrid.DataSource = dataTable;
			dataGrid.DataBind();
			dataGrid.RenderControl(writer);
			string path = text.Substring(0, text.LastIndexOf("\\"));
			if (!Directory.Exists(path))
			{
				Directory.CreateDirectory(path);
			}
			StreamWriter streamWriter = new StreamWriter(text, append: true);
			stringWriter.ToString().Normalize();
			streamWriter.Write(stringWriter.ToString());
			streamWriter.Flush();
			streamWriter.Close();
			WriteAttachment(fileInfo.Name, "application/vnd.ms-excel", stringWriter.ToString());
		}
		catch (Exception)
		{
			string empty = string.Empty;
			empty = "No Records to Export.";
			base.ClientScript.RegisterStartupScript(GetType(), "myalert", "alert('" + empty + "');", addScriptTags: true);
		}
	}

	public static void WriteAttachment(string FileName, string FileType, string content)
	{
		try
		{
			HttpResponse response = HttpContext.Current.Response;
			response.ClearHeaders();
			response.AppendHeader("Content-Disposition", "attachment; filename=" + FileName);
			response.ContentType = FileType;
			response.Write(content);
			response.End();
		}
		catch (Exception)
		{
		}
	}

	protected void btnCancel_Click(object sender, EventArgs e)
	{
		base.Response.Redirect("~/Module/Inventory/Reports/Search.aspx");
	}
}
