# Generated by Django 5.2.7 on 2025-11-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblqcAuthorizedmcn',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(db_column='SysDate', max_length=50)),
                ('systime', models.CharField(db_column='SysTime', max_length=50)),
                ('compid', models.IntegerField(db_column='CompId')),
                ('finyearid', models.IntegerField(db_column='FinYearId')),
                ('sessionid', models.CharField(db_column='SessionId', max_length=50)),
                ('mcnid', models.IntegerField(blank=True, db_column='MCNId', null=True)),
                ('mcndid', models.IntegerField(blank=True, db_column='MCNDId', null=True)),
                ('qaqty', models.FloatField(blank=True, db_column='QAQty', null=True)),
            ],
            options={
                'db_table': 'tblQc_AuthorizedMCN',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblqcMaterialqualityDetails',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('gqnno', models.TextField(blank=True, db_column='GQNNo', null=True)),
                ('grrid', models.IntegerField(blank=True, db_column='GRRId', null=True)),
                ('normalaccqty', models.FloatField(blank=True, db_column='NormalAccQty', null=True)),
                ('acceptedqty', models.FloatField(blank=True, db_column='AcceptedQty', null=True)),
                ('deviatedqty', models.FloatField(blank=True, db_column='DeviatedQty', null=True)),
                ('segregatedqty', models.FloatField(blank=True, db_column='SegregatedQty', null=True)),
                ('rejectedqty', models.FloatField(blank=True, db_column='RejectedQty', null=True)),
                ('rejectionreason', models.IntegerField(blank=True, db_column='RejectionReason', null=True)),
                ('sn', models.TextField(blank=True, db_column='SN', null=True)),
                ('pn', models.TextField(blank=True, db_column='PN', null=True)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
            ],
            options={
                'db_table': 'tblQc_MaterialQuality_Details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblqcMaterialqualityMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(db_column='SysDate', max_length=50)),
                ('systime', models.CharField(db_column='SysTime', max_length=50)),
                ('compid', models.IntegerField(db_column='CompId')),
                ('finyearid', models.IntegerField(db_column='FinYearId')),
                ('sessionid', models.TextField(db_column='SessionId')),
                ('gqnno', models.TextField(blank=True, db_column='GQNNo', null=True)),
                ('grrno', models.TextField(blank=True, db_column='GRRNo', null=True)),
                ('grrid', models.IntegerField(blank=True, db_column='GRRId', null=True)),
            ],
            options={
                'db_table': 'tblQc_MaterialQuality_Master',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblqcMaterialreturnqualityDetails',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('mrqnno', models.TextField(blank=True, db_column='MRQNNo', null=True)),
                ('mrnid', models.IntegerField(blank=True, db_column='MRNId', null=True)),
                ('acceptedqty', models.FloatField(blank=True, db_column='AcceptedQty', null=True)),
                ('rejectedqty', models.FloatField(blank=True, db_column='RejectedQty', null=True)),
            ],
            options={
                'db_table': 'tblQc_MaterialReturnQuality_Details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblqcMaterialreturnqualityMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(db_column='SysDate', max_length=50)),
                ('systime', models.CharField(db_column='SysTime', max_length=50)),
                ('compid', models.IntegerField(db_column='CompId')),
                ('finyearid', models.IntegerField(db_column='FinYearId')),
                ('sessionid', models.TextField(db_column='SessionId')),
                ('mrqnno', models.TextField(blank=True, db_column='MRQNNo', null=True)),
                ('mrnno', models.TextField(blank=True, db_column='MRNNo', null=True)),
                ('mrnid', models.IntegerField(blank=True, db_column='MRNId', null=True)),
            ],
            options={
                'db_table': 'tblQc_MaterialReturnQuality_Master',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblqcRejectionReason',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('symbol', models.TextField(blank=True, db_column='Symbol', null=True)),
            ],
            options={
                'db_table': 'tblQc_Rejection_Reason',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblqcScrapregister',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(db_column='SysDate', max_length=50)),
                ('systime', models.CharField(db_column='SysTime', max_length=50)),
                ('compid', models.IntegerField(db_column='CompId')),
                ('finyearid', models.IntegerField(db_column='FinYearId')),
                ('sessionid', models.CharField(db_column='SessionId', max_length=50)),
                ('mrqnid', models.IntegerField(blank=True, db_column='MRQNId', null=True)),
                ('mrqndid', models.IntegerField(blank=True, db_column='MRQNDId', null=True)),
                ('itemid', models.CharField(blank=True, db_column='ItemId', max_length=50, null=True)),
                ('scrapno', models.TextField(blank=True, db_column='ScrapNo', null=True)),
                ('qty', models.FloatField(blank=True, db_column='Qty', null=True)),
            ],
            options={
                'db_table': 'tblQC_Scrapregister',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
