<%@ page language="C#" masterpagefile="~/MasterPage.master" autoeventwireup="true" inherits="Module_Inventory_Transactions_WIS_ActualRun_Assembly, newerp_deploy" title="ERP" %>
<%@ Register TagPrefix="telerik" Namespace="Telerik.Web.UI" Assembly="Telerik.Web.UI" %>
<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <link href="../../../Css/yui-datatable.css" rel="stylesheet" type="text/css" />
    <link href="../../../Css/styles.css" rel="stylesheet" type="text/css" />
    <link href="../../../Css/StyleSheet.css" rel="stylesheet" type="text/css" />
    </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cp3" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="cp1" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="cp2" Runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="MainContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content6" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
</asp:Content>
<asp:Content ID="Content7" ContentPlaceHolderID="ContentPlaceHolder3" Runat="Server">
    
    <script type="text/javascript">
var prm = Sys.WebForms.PageRequestManager.getInstance();
//Raised before processing of an asynchronous postback starts and the postback request is sent to the server.
prm.add_beginRequest(BeginRequestHandler);
// Raised after an asynchronous postback is finished and control has been returned to the browser.
prm.add_endRequest(EndRequestHandler);
function BeginRequestHandler(sender, args) {
//Shows the modal popup - the update progress
var popup = $find('<%= modalPopup.ClientID %>');
if (popup != null) {
popup.show();
}
}

function EndRequestHandler(sender, args) {
//Hide the modal popup - the update progress
var popup = $find('<%= modalPopup.ClientID %>');
if (popup != null) {
popup.hide();
}
}
</script>
<div>
    <asp:UpdateProgress ID="UpdateProgress" runat="server">
<ProgressTemplate>
<asp:Image ID="Image1" ImageUrl="~/images/spinner-big.gif" AlternateText="Processing" runat="server" />
</ProgressTemplate>
</asp:UpdateProgress>
<cc1:ModalPopupExtender ID="modalPopup" runat="server" TargetControlID="UpdateProgress"
PopupControlID="UpdateProgress" BackgroundCssClass="modalPopup" />
<asp:UpdatePanel ID="pnlData" runat="server" UpdateMode="Conditional">
<ContentTemplate>
    
    <table width="100%" cellpadding="0" cellspacing="0" >                             
    <tr>
<td align="left" height="25">&nbsp;<b>WIS Dry Run of Assembly for Work Order No.:</b>
    <asp:Label ID="Label2" runat="server"></asp:Label>
    &nbsp;&nbsp; <asp:CheckBox  runat="server" ID="CheckBox1"
AutoPostBack="True"  Visible="true" oncheckedchanged="CheckBox1_CheckedChanged" /><b>Expand Tree &nbsp;&nbsp;<asp:Button 
        ID="Button1" runat="server" CssClass="redbox" 
        Text="Actual Run of Assembly" onclick="Button1_Click" Visible="False" />
    &nbsp;<asp:Button ID="Button2" runat="server" CssClass="redbox" 
        onclick="Button2_Click" Text="Dry Run of Material" />
&nbsp;<asp:Button ID="btnCancel" runat="server" CssClass="redbox" 
        onclick="btnCancel_Click" Text="Cancel" />
&nbsp;&nbsp;&nbsp; &nbsp;<asp:Label ID="lblmsg" runat="server"  
        style="color: #FF3300; font-weight: 700"></asp:Label>
</b></td>
    </tr>
                      
    <tr>
<td>

<telerik:RadAjaxLoadingPanel ID="RadAjaxLoadingPanel1" runat="server" 
        Height="16px" >       
      </telerik:RadAjaxLoadingPanel>    
    <telerik:RadAjaxPanel ID="RadAjaxPanel1" LoadingPanelID="RadAjaxLoadingPanel1" 
        runat="server" Width="100%" HorizontalAlign="NotSet"> 
                   
        <telerik:RadTreeList runat="server" ID="RadTreeList1" AllowPaging="false" PageSize="15"
            DataKeyNames="CId" OnItemCommand="RadTreeList1_ItemCommand"           
            OnPageSizeChanged="RadTreeList1_PageSizeChanged" OnPageIndexChanged="RadTreeList1_PageIndexChanged"
            ParentDataKeyNames="PId"
            onautogeneratedcolumncreated="RadTreeList1_AutoGeneratedColumnCreated" 
             CssClass="yui-datatable-theme">        
            
            <Columns>            
                        <telerik:TreeListBoundColumn DataField="CId" HeaderText="Assembly" 
                            UniqueName="CId"  Visible="False
                            "/>
                         <telerik:TreeListBoundColumn DataField="WONo" HeaderText="WorkOrder" 
                            UniqueName="WONo"  Visible="False"/>
                          <telerik:TreeListBoundColumn DataField="PId" HeaderText="Parent Node" 
                            UniqueName="PId" Visible="False"/>
                            <telerik:TreeListBoundColumn DataField="ItemId" HeaderText="ItemId" 
                            UniqueName="ItemId"  Visible="False"/>                            
                            <telerik:TreeListBoundColumn DataField="Unit Qty" HeaderText="Quantity" 
                            UniqueName="Unit Qty"  Visible="False"/>
                         <telerik:TreeListBoundColumn DataField="Weld" HeaderText="Weldments" 
                            UniqueName="Weld"  Visible="False"/> 
                            
                             <telerik:TreeListTemplateColumn HeaderStyle-Width="80px">                                
                                <ItemTemplate>
                                
                                   <telerik:RadButton ID="SelectButton" runat="server" Text="" CommandName="Select" Width="16px" Height="16px">
                                  <Image ImageUrl="../../../images/export.ico" />
                                  
                                  </telerik:RadButton>
                                   
                                </ItemTemplate>
                                
                                <HeaderStyle Width="80px" />
                          
                            </telerik:TreeListTemplateColumn>
                                                                  
            </Columns>
            <PagerStyle CssClass="fontcss" />
            
            <HeaderStyle Font-Bold="True" CssClass="fontcss" />
            
            <SelectedItemStyle CssClass="fontcss" />
            
            <PagerTemplate>
                <table width="100%">
                    <tr>
                        <td align="center" width="7%">
<asp:Button ID="btnPageFirst" runat="server" Text=" " CssClass="rtlPageFirst" CommandName="Page"
CommandArgument="First" />
<asp:Button ID="btnPagePrev" runat="server" Text=" " CssClass="rtlPagePrev" CommandName="Page"
CommandArgument="Prev" /> 
                        </td>
                        <td align="center" width="4%">
                        <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                        </td>
                        <td align="center" width="6%">
                        <asp:Panel runat="server" ID="TreeListPagerPlaceHolder" />
<asp:Button ID="btnPageNext" runat="server" Text=" " CssClass="rtlPageNext" CommandName="Page"
CommandArgument="Next" />
<asp:Button ID="btnPageLast" runat="server" Text=" " CssClass="rtlPageLast" CommandName="Page"
CommandArgument="Last" />
<td>
    <asp:ImageButton ID="ImageButton1" runat="server" ImageUrl="../../../images/export.ico" OnClick="ImageButton1_Click" />
</td>

        </td>
        <td align="right">
                Displaying page
                <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                of
                <%# (int)DataBinder.Eval(Container, "Paging.PageCount") %>
                / Items
                <%# (int)DataBinder.Eval(Container, "Paging.FirstIndexInPage") + 1 %>
                to
                <%# (int)DataBinder.Eval(Container, "Paging.LastIndexInPage") + 1 %>
                of
                <%# DataBinder.Eval(Container, "Paging.DataSourceCount")%>
        </td>
                    </tr>
                </table>
            </PagerTemplate>
            
        </telerik:RadTreeList>  
        <br />
        
     </telerik:RadAjaxPanel>
    </td>
</tr>  
    </table>
    </ContentTemplate>
    </asp:UpdatePanel>
    </div>
    
</asp:Content>
<asp:Content ID="Content8" ContentPlaceHolderID="ContentPlaceHolder4" Runat="Server">
</asp:Content>

