# Generated by Django 5.2.7 on 2025-11-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblmroffice',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(blank=True, db_column='SysDate', max_length=50, null=True)),
                ('systime', models.CharField(blank=True, db_column='SysTime', max_length=50, null=True)),
                ('compid', models.IntegerField(blank=True, db_column='CompId', null=True)),
                ('sessionid', models.CharField(blank=True, db_column='SessionId', max_length=50, null=True)),
                ('finyearid', models.IntegerField(blank=True, db_column='FinYearId', null=True)),
                ('formodule', models.IntegerField(blank=True, db_column='ForModule', null=True)),
                ('format', models.TextField(blank=True, db_column='Format', null=True)),
                ('filename', models.TextField(blank=True, db_column='FileName', null=True)),
                ('size', models.TextField(blank=True, db_column='Size', null=True)),
                ('contenttype', models.TextField(blank=True, db_column='ContentType', null=True)),
                ('data', models.BinaryField(blank=True, db_column='Data', null=True)),
            ],
            options={
                'verbose_name': 'MR Office Document',
                'verbose_name_plural': 'MR Office Documents',
                'db_table': 'tblMROffice',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
