<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="BOM_Design_WO_TreeView_Edit.aspx.cs" Inherits="Module_Design_Transactions_BOM_Design_WO_TreeView_Edit" %>
<%@ Register TagPrefix="telerik" Namespace="Telerik.Web.UI" Assembly="Telerik.Web.UI" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

 <link href="../../../Css/yui-datatable.css" rel="stylesheet" type="text/css" />
    <link href="../../../Css/StyleSheet.css" rel="stylesheet" type="text/css" />
<script src="../../../Javascript/loadingNotifier.js" type="text/javascript"></script>
    <style type="text/css">
        .style1
        {
            width: 525px;
        }
        .style2
        {
            width: 225px;
        }
        .style3
        {
            width: 31px;
        }
        .style4
        {
            width: 985px;
        }
        .style5
        {
            width: 69px;
        }
    </style>
    
    


</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="cp3" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="cp1" Runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="cp2" Runat="Server">
</asp:Content>
<asp:Content ID="Content6" ContentPlaceHolderID="MainContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content7" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
</asp:Content>
<asp:Content ID="Content8" ContentPlaceHolderID="ContentPlaceHolder3" Runat="Server">




<table width="98%">
<tr>
<td align="left" class="style3">
    
    <table align="left" cellpadding="0" cellspacing="0" class="style4">
        <tr>
            <td class="style5" align="center">
                <b>Edit BOM</b></td>
            <td class="style1">
                <b>&nbsp;Wo No:</b>
    <asp:Label ID="Label2" runat="server"></asp:Label>
            </td>
            <td class="style2">
             <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" 
                    CssClass="box3" onselectedindexchanged="DropDownList1_SelectedIndexChanged">
                    <asp:ListItem Selected="True" Value="0">All</asp:ListItem>
                    <asp:ListItem Value="1">BoughtOut</asp:ListItem>
                    <asp:ListItem Value="2">Manufacturing</asp:ListItem>
                </asp:DropDownList>
                <asp:Label ID="lblMsg" runat="server" style="color: #FF0000"></asp:Label>
             </td>
            <td class="style12">
                <asp:CheckBox ID="CheckBox1" runat="server" AutoPostBack="True" 
        oncheckedchanged="CheckBox1_CheckedChanged" />
                <b>Expand Tree&nbsp; </b>
            &nbsp;
                <asp:Button ID="Button1" runat="server" CssClass="redbox" Font-Bold="False" 
                    onclick="Button1_Click" Text="Cancel" />
            </td>
        </tr>
    </table>
            
    </td>
</tr>
<tr>
<td height="277" valign="top">

<%--<telerik:RadAjaxLoadingPanel ID="RadAjaxLoadingPanel1" runat="server"
        MinDisplayTime="0" >
    </telerik:RadAjaxLoadingPanel>
    
    <telerik:RadAjaxPanel ID="RadAjaxPanel1" LoadingPanelID="RadAjaxLoadingPanel1" runat="server" Width="100%" >
        --%>
        
    <asp:Panel ID="Panel1" ScrollBars="Auto"  runat="server">
   
        <telerik:RadTreeList runat="server" ID="RadTreeList1" PageSize="20" 
            DataKeyNames="CId" OnItemCommand="RadTreeList1_ItemCommand" AllowRecursiveSelection="True" 
            OnPageSizeChanged="RadTreeList1_PageSizeChanged" OnPageIndexChanged="RadTreeList1_PageIndexChanged"
            ParentDataKeyNames="PId" 
            onautogeneratedcolumncreated="RadTreeList1_AutoGeneratedColumnCreated" 
            AllowMultiItemSelection="True" CssClass="yui-datatable-theme"> 
           
            <AlternatingItemStyle CssClass="fontcss" />
            <ItemStyle CssClass="fontcss" />
            
            <Columns>
            
                                               
                        <telerik:TreeListTemplateColumn  Visible="false">                                
                                <ItemTemplate>
                                    <asp:Label ID="lblCId" runat="server" Text='<%# Bind("CId") %>' ></asp:Label> 
                                </ItemTemplate>        
                            </telerik:TreeListTemplateColumn> 
                             <telerik:TreeListTemplateColumn  Visible="false">                                
                                <ItemTemplate>
                                    <asp:Label ID="lblWONo" runat="server" Text='<%# Bind("WONo") %>'></asp:Label> 
                                </ItemTemplate>        
                            </telerik:TreeListTemplateColumn>                           
                              <telerik:TreeListTemplateColumn Visible="false" >                                
                                <ItemTemplate>
                                    <asp:Label ID="lblPId" runat="server" Text='<%# Bind("PId") %>' ></asp:Label> 
                                </ItemTemplate>        
                            </telerik:TreeListTemplateColumn>
                             
                              <telerik:TreeListTemplateColumn  Visible="false" >                                
                                <ItemTemplate>
                                    <asp:Label ID="lblId" runat="server" Text='<%# Bind("Id") %>' ></asp:Label> 
                                </ItemTemplate>        
                            </telerik:TreeListTemplateColumn>                            
   
                            <telerik:TreeListTemplateColumn Visible="false">                                
                                <ItemTemplate>
                                    <asp:Label ID="lblItemId" runat="server" Text='<%# Bind("ItemId") %>' ></asp:Label> 
                                </ItemTemplate>        
                            </telerik:TreeListTemplateColumn>
                      <telerik:TreeListTemplateColumn HeaderStyle-Width="80px">                                
                                <ItemTemplate>
                                
                                   <telerik:RadButton ID="SelectButton" runat="server" Text="" CommandName="Sel" Width="16px" Height="16px">
                                  <Image ImageUrl="../../../images/Add.PNG" />
                                  </telerik:RadButton>
                                   
                                </ItemTemplate>
                               
                          
                                <HeaderStyle Width="80px" />
                          
                            </telerik:TreeListTemplateColumn>
                            
                            <telerik:TreeListTemplateColumn HeaderStyle-Width="8%" ItemStyle-HorizontalAlign="Center" HeaderStyle-HorizontalAlign="Center" HeaderText="Drw/Image">  
                            
                                                        <ItemTemplate >
                                                            
                                                                
                                                            <asp:LinkButton ID="btnlnkImg" CommandName="downloadImg" Visible="true"  Text='<%# Bind("FileName") %>' runat="server"></asp:LinkButton>
                                                            <asp:LinkButton ID="lnkUploadImg" CommandName="uploadImg" Visible="true" Text='<%# Bind("uploadImg") %>' runat="server"></asp:LinkButton>
                                                        </ItemTemplate>
                                                      
                                                       
                                                        <HeaderStyle HorizontalAlign="Center" Width="8%" />
                                                        <ItemStyle HorizontalAlign="Center" />
                                                      
                                                       
                                                </telerik:TreeListTemplateColumn>                                               
                                                
                                               
                                                 <telerik:TreeListTemplateColumn  HeaderText="Spec. Sheet" HeaderStyle-Width="8%" ItemStyle-HorizontalAlign="Center" HeaderStyle-HorizontalAlign="Center">  
                                                    <ItemTemplate>
                                                        <asp:LinkButton ID="btnlnkSpec" CommandName="downloadSpec" Visible="true"  Text='<%# Bind("AttName") %>'  runat="server"></asp:LinkButton>
                          <asp:LinkButton ID="lnkUploadSpec" CommandName="uploadSpec" Visible="true" Text='<%# Bind("uploadSpec") %>' runat="server"></asp:LinkButton>
                                                               
                                                    </ItemTemplate>                                                  
                                                   
                                                     <HeaderStyle HorizontalAlign="Center" Width="8%" />
                                                     <ItemStyle HorizontalAlign="Center" />
                                                   
                                               </telerik:TreeListTemplateColumn>
                                               
                                               
                                           <telerik:TreeListTemplateColumn  HeaderText="Amd No" HeaderStyle-Width="8%" ItemStyle-HorizontalAlign="Center" HeaderStyle-HorizontalAlign="Center">  
                                                    <ItemTemplate>
                                                        <asp:LinkButton ID="BtnAmdNo" CommandName="Amd" Visible="true"  Text='<%# Bind("AmdNo") %>'  runat="server"></asp:LinkButton>
                          
                                                               
                                                    </ItemTemplate>                                                  
                                                   
                                                     <HeaderStyle HorizontalAlign="Center" Width="6%" />
                                                     <ItemStyle HorizontalAlign="Center" />
                                                   
                                               </telerik:TreeListTemplateColumn>    
                                               
                                               
                                               
                                               
            </Columns>
            
            
            <PagerStyle CssClass="fontcss" />
            
            <HeaderStyle Font-Bold="True" CssClass="fontcss" />
            
            <SelectedItemStyle CssClass="fontcss" />
            
            <PagerTemplate>
                <table width="100%">
                    <tr>
                        <td align="center" width="7%">
<asp:Button ID="btnPageFirst" runat="server" Text=" " CssClass="rtlPageFirst" CommandName="Page"
CommandArgument="First" />
<asp:Button ID="btnPagePrev" runat="server" Text=" " CssClass="rtlPagePrev" CommandName="Page"
CommandArgument="Prev" /> 
                        </td>
                        <td align="center" width="4%">
                        <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                        </td>
                        <td align="center" width="6%">
                        <asp:Panel runat="server" ID="TreeListPagerPlaceHolder" />
<asp:Button ID="btnPageNext" runat="server" Text=" " CssClass="rtlPageNext" CommandName="Page"
CommandArgument="Next" />
<asp:Button ID="btnPageLast" runat="server" Text=" " CssClass="rtlPageLast" CommandName="Page"
CommandArgument="Last" />
                        </td>
                        <td align="right">
                                Displaying page
                                <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                                of
                                <%# (int)DataBinder.Eval(Container, "Paging.PageCount") %>
                                / Items
                                <%# (int)DataBinder.Eval(Container, "Paging.FirstIndexInPage") + 1 %>
                                to
                                <%# (int)DataBinder.Eval(Container, "Paging.LastIndexInPage") + 1 %>
                                of
                                <%# DataBinder.Eval(Container, "Paging.DataSourceCount")%>
                        </td>
                    </tr>
                </table>
            </PagerTemplate>
        </telerik:RadTreeList>      
     </asp:Panel>
     
    </td>
</tr>  
    </table>









</asp:Content>
<asp:Content ID="Content9" ContentPlaceHolderID="ContentPlaceHolder4" Runat="Server">
</asp:Content>

