<%@ page language="C#" masterpagefile="~/MasterPage.master" autoeventwireup="true" inherits="Module_Design_Transactions_TPL_Design_WO_TreeView_Delete, newerp_deploy" title="ERP" theme="Default" %>

<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
<link href="../../../Css/yui-datatable.css" rel="stylesheet" type="text/css" />
    <link href="../../../Css/StyleSheet.css" rel="stylesheet" type="text/css" />
    <script src="../../../Javascript/loadingNotifier.js" type="text/javascript"></script>
    
    <script src="../../../Javascript/PopUpMsg.js" type="text/javascript"></script>
    <style type="text/css">

        .style3
        {
            width: 31px;
        }
        .style4
        {
            width: 985px;
        }
        .style5
        {
            width: 84px;
        }
        .style1
        {
            width: 328px;
        }
        .style2
        {
            width: 346px;
        }
        </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cp3" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="cp1" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="cp2" Runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="MainContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content6" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
</asp:Content>
<asp:Content ID="Content7" ContentPlaceHolderID="ContentPlaceHolder3" Runat="Server">
    <table width="100%">
        <tr>
            <td align="left" class="style3">
                <table align="left" cellpadding="0" cellspacing="0" class="style4">
                    <tr>
                        <td class="style5" align="center">
                            <b>Delete TPL</b></td>
                        <td class="style1">
                            <b>&nbsp;Wo No:</b>
                            <asp:Label ID="Label2" runat="server"></asp:Label>
                        </td>
                        <td class="style2">
                            <asp:Label ID="lblMsg" runat="server" style="color: #CC0000"></asp:Label>
                        </td>
                        <td class="style12">
                            <asp:CheckBox ID="CheckBox1" runat="server" AutoPostBack="True" 
        oncheckedchanged="CheckBox1_CheckedChanged" />
                            <b>Expand Tree&nbsp; </b>
                            <asp:Button ID="btnDel" runat="server" CssClass="redbox" onclick="btnDel_Click" 
                              OnClientClick=" return confirmationDelete()"    Text="Delete" />
                            &nbsp;
                            <asp:Button ID="Button1" runat="server" CssClass="redbox" Font-Bold="False" 
                    onclick="Button1_Click" Text="Cancel" />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td height="277" valign="top">
                <telerik:RadAjaxLoadingPanel ID="RadAjaxLoadingPanel1" runat="server"
        MinDisplayTime="0" >
                </telerik:RadAjaxLoadingPanel>
                <telerik:RadAjaxPanel ID="RadAjaxPanel1" LoadingPanelID="RadAjaxLoadingPanel1" runat="server" Width="100%" >
                    
                    
                    
                    
                    <telerik:RadTreeList runat="server" ID="RadTreeList1" AllowPaging="True" PageSize="17"
            DataKeyNames="CId" OnItemCommand="RadTreeList1_ItemCommand"           
            OnPageSizeChanged="RadTreeList1_PageSizeChanged" OnPageIndexChanged="RadTreeList1_PageIndexChanged"
            ParentDataKeyNames="PId"
            onautogeneratedcolumncreated="RadTreeList1_AutoGeneratedColumnCreated" 
             CssClass="yui-datatable-theme">        
             
            <Columns>            
           <telerik:TreeListSelectColumn UniqueName="ck" >
          
               <HeaderStyle Width="60px" />
          
            </telerik:TreeListSelectColumn>
                        <telerik:TreeListBoundColumn DataField="Id" HeaderText="Id" 
                            UniqueName="Id"  Visible="False"/>
                        <telerik:TreeListBoundColumn DataField="CId" HeaderText="Assembly" 
                            UniqueName="CId"  Visible="False
                            "/>
                         <telerik:TreeListBoundColumn DataField="WONo" HeaderText="WorkOrder" 
                            UniqueName="WONo"  Visible="False"/>
                          <telerik:TreeListBoundColumn DataField="PId" HeaderText="Parent Node" 
                            UniqueName="PId" Visible="False"/>
                            <telerik:TreeListBoundColumn DataField="ItemId" HeaderText="ItemId" 
                            UniqueName="ItemId"  Visible="False"/>                            
                            <telerik:TreeListBoundColumn DataField="Unit Qty" HeaderText="Quantity" 
                            UniqueName="Unit Qty"  Visible="False"/>
                         
                                                                  
            </Columns>
            <PagerStyle CssClass="fontcss" />
            
            <HeaderStyle Font-Bold="True" CssClass="fontcss" />
            
            <SelectedItemStyle CssClass="fontcss" />
            
            <PagerTemplate>
                <table width="100%">
                    <tr>
                        <td align="center" width="7%">
<asp:Button ID="btnPageFirst" runat="server" Text=" " CssClass="rtlPageFirst" CommandName="Page"
CommandArgument="First" />
<asp:Button ID="btnPagePrev" runat="server" Text=" " CssClass="rtlPagePrev" CommandName="Page"
CommandArgument="Prev" /> 
                        </td>
                        <td align="center" width="4%">
                        <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                        </td>
                        <td align="center" width="6%">
                        <asp:Panel runat="server" ID="TreeListPagerPlaceHolder" />
<asp:Button ID="btnPageNext" runat="server" Text=" " CssClass="rtlPageNext" CommandName="Page"
CommandArgument="Next" />
<asp:Button ID="btnPageLast" runat="server" Text=" " CssClass="rtlPageLast" CommandName="Page"
CommandArgument="Last" />

                        </td>
                        <td align="right">
                                Displaying page
                                <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                                of
                                <%# (int)DataBinder.Eval(Container, "Paging.PageCount") %>
                                / Items
                                <%# (int)DataBinder.Eval(Container, "Paging.FirstIndexInPage") + 1 %>
                                to
                                <%# (int)DataBinder.Eval(Container, "Paging.LastIndexInPage") + 1 %>
                                of
                                <%# DataBinder.Eval(Container, "Paging.DataSourceCount")%>
                        </td>
                    </tr>
                </table>
            </PagerTemplate>
          
            
        </telerik:RadTreeList>  
        
                </telerik:RadAjaxPanel>
            </td>
        </tr>
    </table>
</asp:Content>
<asp:Content ID="Content8" ContentPlaceHolderID="ContentPlaceHolder4" Runat="Server">
</asp:Content>

