<%@ page language="C#" masterpagefile="~/MasterPage.master" autoeventwireup="true" inherits="Module_Design_Transactions_ItemTree, newerp_deploy" title="ERP" theme="Default" %>
<%@ Register TagPrefix="telerik" Namespace="Telerik.Web.UI" Assembly="Telerik.Web.UI" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <link href="../../../Css/yui-datatable.css" rel="stylesheet" type="text/css" />
    <link href="../../../Css/StyleSheet.css" rel="stylesheet" type="text/css" />
    <script src="../../../Javascript/loadingNotifier.js" type="text/javascript"></script>
    <style type="text/css">
        .style3
        {
            height: 23px;
            }
        .style4
        {
            width: 100%;
        }
        .style5
        {
            width: 162px;
        }
        .style7
        {
            width: 44px;
        }
        .style8
        {
            width: 388px;
        }
        .style12
        {
        }
    </style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cp3" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="cp1" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="cp2" Runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="MainContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content6" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
</asp:Content>
<asp:Content ID="Content7" ContentPlaceHolderID="ContentPlaceHolder3" Runat="Server">

<table width="100%">
<tr>
<td align="left" class="style3">
    
    <table align="left" cellpadding="0" cellspacing="0" class="style4">
        <tr>
            <td class="style7" align="center">
                <b>TPL</b></td>
            <td class="style5">
                <b>Wo No:</b>
    <asp:Label ID="Label2" runat="server"></asp:Label>
            </td>
            <td class="style8">
                <asp:Label ID="lblmsg" runat="server" style="color: #CC0000"></asp:Label>
            </td>
            <td class="style12">
                <asp:CheckBox ID="CheckBox1" runat="server" AutoPostBack="True" 
        oncheckedchanged="CheckBox1_CheckedChanged" />
                <b>Expand Tree&nbsp;&nbsp; &nbsp;&nbsp; Root Assembly&nbsp; </b>
<%--                <asp:Button ID="btnAssembly" runat="server" Text=" Add "  
        Font-Bold="False" CssClass="redbox" 
        onclick="btnAssembly_Click" />
            &nbsp;--%>
            
            <asp:Button ID="btnCopy" runat="server" CssClass="redbox" 
                    onclick="btnCopy_Click" Text="Copy From" />
&nbsp;<asp:Button ID="Button1" runat="server" CssClass="redbox" Font-Bold="False" 
                    onclick="Button1_Click" Text="Cancel" />
            </td>
        </tr>
    </table>
            
    </td>
</tr>
<tr>
<td height="277" valign="top">

<%--<telerik:RadAjaxLoadingPanel ID="RadAjaxLoadingPanel1" runat="server"
        MinDisplayTime="0" >
    </telerik:RadAjaxLoadingPanel>
    
    <telerik:RadAjaxPanel ID="RadAjaxPanel1" LoadingPanelID="RadAjaxLoadingPanel1" runat="server" Width="100%" >
        
        <telerik:RadTreeList runat="server" ID="RadTreeList1" AllowPaging="True" PageSize="17" 
            DataKeyNames="CId" OnItemCommand="RadTreeList1_ItemCommand" AllowRecursiveSelection="True" 
            OnPageSizeChanged="RadTreeList1_PageSizeChanged" OnPageIndexChanged="RadTreeList1_PageIndexChanged"
            ParentDataKeyNames="PId" 
            onautogeneratedcolumncreated="RadTreeList1_AutoGeneratedColumnCreated" 
            AllowMultiItemSelection="True" CssClass="yui-datatable-theme"> 
           
            <AlternatingItemStyle CssClass="fontcss" />
            <ItemStyle CssClass="fontcss" />
            
            <Columns>
            
                        <telerik:TreeListBoundColumn DataField="CId" HeaderText="Assembly" UniqueName="CId"  Visible="false"/>
                        <telerik:TreeListBoundColumn DataField="WONo" HeaderText="WorkOrder" UniqueName="WONo"  Visible="false"/>
                        <telerik:TreeListBoundColumn DataField="PId" HeaderText="Parent Node" UniqueName="PId" Visible="false"/>
                        <telerik:TreeListBoundColumn DataField="ItemId" HeaderText="Item Id" UniqueName="ItemId" Visible="false"/>
                             
                      <telerik:TreeListTemplateColumn HeaderStyle-Width="80px">                                
                                <ItemTemplate>
                                
                                   <telerik:RadButton ID="SelectButton" runat="server" Text="" CommandName="Select" Width="16px" Height="16px">
                                  <Image ImageUrl="../../../images/Add.PNG" />
                                  </telerik:RadButton>
                                   
                                </ItemTemplate>
                               
                          
                                <HeaderStyle Width="80px" />
                          
                            </telerik:TreeListTemplateColumn>
            </Columns>
            
            
            <PagerStyle CssClass="fontcss" />
            
            <HeaderStyle Font-Bold="True" CssClass="fontcss" />
            
            <SelectedItemStyle CssClass="fontcss" />
            
            <PagerTemplate>
                <table width="100%">
                    <tr>
                        <td align="center" width="7%">
<asp:Button ID="btnPageFirst" runat="server" Text=" " CssClass="rtlPageFirst" CommandName="Page"
CommandArgument="First" />
<asp:Button ID="btnPagePrev" runat="server" Text=" " CssClass="rtlPagePrev" CommandName="Page"
CommandArgument="Prev" /> 
                        </td>
                        <td align="center" width="4%">
                        <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                        </td>
                        <td align="center" width="6%">
                        <asp:Panel runat="server" ID="TreeListPagerPlaceHolder" />
<asp:Button ID="btnPageNext" runat="server" Text=" " CssClass="rtlPageNext" CommandName="Page"
CommandArgument="Next" />
<asp:Button ID="btnPageLast" runat="server" Text=" " CssClass="rtlPageLast" CommandName="Page"
CommandArgument="Last" />
                        </td>
                        <td align="right">
                                Displaying page
                                <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                                of
                                <%# (int)DataBinder.Eval(Container, "Paging.PageCount") %>
                                / Items
                                <%# (int)DataBinder.Eval(Container, "Paging.FirstIndexInPage") + 1 %>
                                to
                                <%# (int)DataBinder.Eval(Container, "Paging.LastIndexInPage") + 1 %>
                                of
                                <%# DataBinder.Eval(Container, "Paging.DataSourceCount")%>
                        </td>
                    </tr>
                </table>
            </PagerTemplate>
        </telerik:RadTreeList>      
    </telerik:RadAjaxPanel>--%>
 
 <asp:Panel ID="Panel1" ScrollBars="Auto" runat="server">
   
        <telerik:RadTreeList runat="server" ID="RadTreeList1" AllowPaging="True" PageSize="20"  
            DataKeyNames="CId" OnItemCommand="RadTreeList1_ItemCommand" AllowRecursiveSelection="True" 
            OnPageSizeChanged="RadTreeList1_PageSizeChanged" OnPageIndexChanged="RadTreeList1_PageIndexChanged"
            ParentDataKeyNames="PId"  
            onautogeneratedcolumncreated="RadTreeList1_AutoGeneratedColumnCreated" 
            AllowMultiItemSelection="false" CssClass="yui-datatable-theme"> 
           
            <AlternatingItemStyle CssClass="fontcss" />
            <ItemStyle CssClass="fontcss" />
            
            <Columns>
            
                                                  
                            
                             <telerik:TreeListTemplateColumn Visible="false" >                                
                                <ItemTemplate>
                                
                                    <asp:Label ID="lblCId" runat="server" Visible="false" Text='<%# Bind("CId") %>'></asp:Label>
                                   
                                </ItemTemplate>                           
                            </telerik:TreeListTemplateColumn>
                            
                            <telerik:TreeListTemplateColumn Visible="false" >                                
                                <ItemTemplate>
                                
                                    <asp:Label ID="lblWONo" runat="server" Visible="false" Text='<%# Bind("WONo") %>'></asp:Label>
                                   
                                </ItemTemplate>                           
                            </telerik:TreeListTemplateColumn>
                             <telerik:TreeListTemplateColumn Visible="false" >                                
                                <ItemTemplate>
                                
                                    <asp:Label ID="lblPId" runat="server" Visible="false" Text='<%# Bind("PId") %>'></asp:Label>
                                   
                                </ItemTemplate>                           
                            </telerik:TreeListTemplateColumn>
        
        <telerik:TreeListTemplateColumn Visible="false" >                                
                                <ItemTemplate>
                                
                                    <asp:Label ID="lblItemId" runat="server" Visible="false" Text='<%# Bind("ItemId") %>'></asp:Label>
                                   
                                </ItemTemplate>                           
                            </telerik:TreeListTemplateColumn>
        
                      <telerik:TreeListTemplateColumn HeaderStyle-Width="80px">                                
                                <ItemTemplate>
                                
                                   <telerik:RadButton ID="SelectButton" runat="server" Text="" Visible="true"  CommandName="Sel" Width="16px" Height="16px">
                                  <Image ImageUrl="../../../images/Add.PNG" />
                                  </telerik:RadButton>
                                   
                                </ItemTemplate>                              
                          
                                <HeaderStyle Width="80px" />
                          
                            </telerik:TreeListTemplateColumn>
                            
                            
                             <telerik:TreeListTemplateColumn HeaderStyle-Width="8%" ItemStyle-HorizontalAlign="Center" HeaderStyle-HorizontalAlign="Center" HeaderText="Drw/Image">  
                            
                                                        <ItemTemplate >
                                                            
                                                                
                                                            <asp:LinkButton ID="btnlnkImg" CommandName="downloadImg" Visible="true"  Text='<%# Bind("FileName") %>' runat="server"></asp:LinkButton>
                                                            <asp:LinkButton ID="lnkUploadImg" CommandName="uploadImg" Visible="true" Text='<%# Bind("uploadImg") %>' runat="server"></asp:LinkButton>
                                                        </ItemTemplate>
                                                      
                                                       
                                                </telerik:TreeListTemplateColumn>                                               
                                                
                                               
                                                 <telerik:TreeListTemplateColumn  HeaderText="Spec. Sheet" HeaderStyle-Width="8%" ItemStyle-HorizontalAlign="Center" HeaderStyle-HorizontalAlign="Center">  
                                                    <ItemTemplate>
                                                        <asp:LinkButton ID="btnlnkSpec" CommandName="downloadSpec" Visible="true"  Text='<%# Bind("AttName") %>'  runat="server"></asp:LinkButton>
                          <asp:LinkButton ID="lnkUploadSpec" CommandName="uploadSpec" Visible="true" Text='<%# Bind("uploadSpec") %>' runat="server"></asp:LinkButton>
                                                               
                                                    </ItemTemplate>                                                  
                                                   
                                               </telerik:TreeListTemplateColumn>
            </Columns>
            
            
            <PagerStyle CssClass="fontcss" />
            
            <HeaderStyle Font-Bold="True" CssClass="fontcss" />
            
            <SelectedItemStyle CssClass="fontcss" />
            
            <PagerTemplate>
                <table width="100%">
                    <tr>
                        <td align="center" width="7%">
<asp:Button ID="btnPageFirst" runat="server" Text=" " CssClass="rtlPageFirst" CommandName="Page"
CommandArgument="First" />
<asp:Button ID="btnPagePrev" runat="server" Text=" " CssClass="rtlPagePrev" CommandName="Page"
CommandArgument="Prev" /> 
                        </td>
                        <td align="center" width="4%">
                        <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                        </td>
                        <td align="center" width="6%">
                        <asp:Panel runat="server" ID="TreeListPagerPlaceHolder" />
<asp:Button ID="btnPageNext" runat="server" Text=" " CssClass="rtlPageNext" CommandName="Page"
CommandArgument="Next" />
<asp:Button ID="btnPageLast" runat="server" Text=" " CssClass="rtlPageLast" CommandName="Page"
CommandArgument="Last" />
                        </td>
                        <td align="right">
                                Displaying page
                                <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                                of
                                <%# (int)DataBinder.Eval(Container, "Paging.PageCount") %>
                                / Items
                                <%# (int)DataBinder.Eval(Container, "Paging.FirstIndexInPage") + 1 %>
                                to
                                <%# (int)DataBinder.Eval(Container, "Paging.LastIndexInPage") + 1 %>
                                of
                                <%# DataBinder.Eval(Container, "Paging.DataSourceCount")%>
                        </td>
                    </tr>
                </table>
            </PagerTemplate>
       </telerik:RadTreeList>  
        </asp:Panel>
     
    </td>
</tr>  
    </table>
</asp:Content>
<asp:Content ID="Content8" ContentPlaceHolderID="ContentPlaceHolder4" Runat="Server">
</asp:Content>

