<%@ page language="C#" autoeventwireup="true" inherits="Module_Design_Transactions_TPL_Design_Copy_Tree, newerp_deploy" theme="Default" %>
<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="cc1" %>
<%@ Register TagPrefix="telerik" Namespace="Telerik.Web.UI" Assembly="Telerik.Web.UI" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>ERP</title>
    <link href="../../../Css/yui-datatable.css" rel="stylesheet" type="text/css" />
    <link href="../../../Css/StyleSheet.css" rel="stylesheet" type="text/css" />
<script src="../../../Javascript/loadingNotifier.js" type="text/javascript"></script>
    <script src="../../../Javascript/PopUpMsg.js" type="text/javascript"></script>
</head>
<body  topmargin="0" bottommargin="0" leftmargin="0" rightmargin="0">
    <form id="form1" runat="server">    
    <table Width="100%" cellpadding="0" cellspacing="0" >                             
    <tr>
<td align="left" class="fontcss">&nbsp;<b>Wo No: </b>
    <asp:Label ID="Label2" runat="server"></asp:Label>
    &nbsp;&nbsp; <asp:CheckBox  runat="server" ID="CheckBox1"
AutoPostBack="True"  Visible="true" oncheckedchanged="CheckBox1_CheckedChanged" /><b>Expand Tree&nbsp;&nbsp;&nbsp;&nbsp;                 <asp:Label ID="lblasslymsg" runat="server" 
        style="color: #FF3300; font-weight: 700"></asp:Label>
                        </b></td>
    </tr>
    
    <tr>
<td>

<telerik:RadAjaxLoadingPanel ID="RadAjaxLoadingPanel1" runat="server" 
        Height="16px" >
       
      </telerik:RadAjaxLoadingPanel>
   
    
    <telerik:RadAjaxPanel ID="RadAjaxPanel1" LoadingPanelID="RadAjaxLoadingPanel1" 
        runat="server" Width="100%" HorizontalAlign="NotSet">
       
        <telerik:RadTreeList runat="server" ID="RadTreeList1" AllowPaging="True" PageSize="8"
            DataKeyNames="CId" OnItemCommand="RadTreeList1_ItemCommand"           
            OnPageSizeChanged="RadTreeList1_PageSizeChanged" OnPageIndexChanged="RadTreeList1_PageIndexChanged"
            ParentDataKeyNames="PId"
            onautogeneratedcolumncreated="RadTreeList1_AutoGeneratedColumnCreated" 
             CssClass="yui-datatable-theme">        
             
            <Columns>            
           <telerik:TreeListSelectColumn UniqueName="ck" >
          
               <HeaderStyle Width="60px" />
          
            </telerik:TreeListSelectColumn>
                        <telerik:TreeListBoundColumn DataField="CId" HeaderText="Assembly" 
                            UniqueName="CId"  Visible="False
                            "/>
                         <telerik:TreeListBoundColumn DataField="WONo" HeaderText="WorkOrder" 
                            UniqueName="WONo"  Visible="False"/>
                          <telerik:TreeListBoundColumn DataField="PId" HeaderText="Parent Node" 
                            UniqueName="PId" Visible="False"/>
                            <telerik:TreeListBoundColumn DataField="ItemId" HeaderText="ItemId" 
                            UniqueName="ItemId"  Visible="False"/>                            
                            <telerik:TreeListBoundColumn DataField="Unit Qty" HeaderText="Quantity" 
                            UniqueName="Unit Qty"  Visible="False"/>
                         <telerik:TreeListBoundColumn DataField="Weld" HeaderText="Weldments" 
                            UniqueName="Weld"  Visible="False"/>
                             <telerik:TreeListBoundColumn DataField="LH" HeaderText="LH" 
                            UniqueName="LH" Visible="False"/>
                            <telerik:TreeListBoundColumn DataField="RH" HeaderText="RH" 
                            UniqueName="RH"  Visible="False"/>
                                                                  
            </Columns>
            <PagerStyle CssClass="fontcss" />
            
            <HeaderStyle Font-Bold="True" CssClass="fontcss" />
            
            <SelectedItemStyle CssClass="fontcss" />
            
            <PagerTemplate>
                <table width="100%">
                    <tr>
                        <td align="center" width="7%">
<asp:Button ID="btnPageFirst" runat="server" Text=" " CssClass="rtlPageFirst" CommandName="Page"
CommandArgument="First" />
<asp:Button ID="btnPagePrev" runat="server" Text=" " CssClass="rtlPagePrev" CommandName="Page"
CommandArgument="Prev" /> 
                        </td>
                        <td align="center" width="4%">
                        <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                        </td>
                        <td align="center" width="6%">
                        <asp:Panel runat="server" ID="TreeListPagerPlaceHolder" />
<asp:Button ID="btnPageNext" runat="server" Text=" " CssClass="rtlPageNext" CommandName="Page"
CommandArgument="Next" />
<asp:Button ID="btnPageLast" runat="server" Text=" " CssClass="rtlPageLast" CommandName="Page"
CommandArgument="Last" />
<td>
<asp:Button ID="btnCopy" runat="server" CssClass="redbox"  OnClientClick=" return confirmationCopy()" 
            onclick="btnCopy_Click" Text="Copy" />
            <asp:Button ID="BtnCancel" runat="server" CssClass="redbox" 
            onclick="BtnCancel_Click" Text="Cancel" />
</td>

                        </td>
                        <td align="right">
                                Displaying page
                                <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                                of
                                <%# (int)DataBinder.Eval(Container, "Paging.PageCount") %>
                                / Items
                                <%# (int)DataBinder.Eval(Container, "Paging.FirstIndexInPage") + 1 %>
                                to
                                <%# (int)DataBinder.Eval(Container, "Paging.LastIndexInPage") + 1 %>
                                of
                                <%# DataBinder.Eval(Container, "Paging.DataSourceCount")%>
                        </td>
                    </tr>
                </table>
            </PagerTemplate>
          
            
        </telerik:RadTreeList>  
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
        
     </telerik:RadAjaxPanel>
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    </td>
</tr>  
    </table>
    
   
    </form>
</body>
</html>
