<%@ page language="C#" masterpagefile="~/MasterPage.master" autoeventwireup="true" inherits="Module_Design_Transactions_TPL_Design_Print_Tree, newerp_deploy" title="ERP" theme="Default" %>
<%@ Register TagPrefix="telerik" Namespace="Telerik.Web.UI" Assembly="Telerik.Web.UI" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
<link href="../../../Css/yui-datatable.css" rel="stylesheet" type="text/css" />
    <link href="../../../Css/StyleSheet.css" rel="stylesheet" type="text/css" />

    <script src="../../../Javascript/loadingNotifier.js" type="text/javascript"></script>
    <style type="text/css">
        .style1
        {
            font-family: Verdana, Arial, Helvetica, sans-serif;
            font-size: 11px;
            font-style: normal;
            line-height: normal;
            font-weight: normal;
            font-variant: normal;
            text-transform: none;
            color: #000000;
            text-decoration: none;
            height: 28px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cp3" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="cp1" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="cp2" Runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="MainContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content6" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
</asp:Content>
<asp:Content ID="Content7" ContentPlaceHolderID="ContentPlaceHolder3" Runat="Server">
<table Width="100%" cellpadding="0" cellspacing="0" >                             
    <tr>
<td align="left" class="style1">&nbsp;<b> TPL Print Wo No: </b>
    <asp:Label ID="Label2" runat="server"></asp:Label>
    &nbsp;&nbsp; <asp:CheckBox  runat="server" ID="CheckBox1"
AutoPostBack="True"  Visible="true" oncheckedchanged="CheckBox1_CheckedChanged" /><b>Expand Tree&nbsp;&nbsp;&nbsp;
    <asp:Button ID="btnCancel" runat="server" CssClass="redbox" 
        onclick="btnCancel_Click" Text="Cancel" />
&nbsp;&nbsp;&nbsp; &nbsp;<asp:Label ID="lblasslymsg" runat="server"  style="color: #FF3300; font-weight: 700"></asp:Label>
</b></td>
    </tr>
                      
    <tr>
<td>

<%--<telerik:RadAjaxLoadingPanel ID="RadAjaxLoadingPanel1" runat="server" 
        Height="16px" >       
      </telerik:RadAjaxLoadingPanel>    --%>
    <telerik:RadAjaxPanel ID="RadAjaxPanel1"  
        runat="server" Width="100%" HorizontalAlign="NotSet"> 
                   
        <telerik:RadTreeList runat="server" ID="RadTreeList1" AllowPaging="True" PageSize="15"
            DataKeyNames="CId" OnItemCommand="RadTreeList1_ItemCommand"           
            OnPageSizeChanged="RadTreeList1_PageSizeChanged" OnPageIndexChanged="RadTreeList1_PageIndexChanged"
            ParentDataKeyNames="PId"
            onautogeneratedcolumncreated="RadTreeList1_AutoGeneratedColumnCreated" 
             CssClass="yui-datatable-theme">        
            
            <Columns>            
                        <telerik:TreeListBoundColumn DataField="CId" HeaderText="Assembly" 
                            UniqueName="CId"  Visible="False
                            "/>
                         <telerik:TreeListBoundColumn DataField="WONo" HeaderText="WorkOrder" 
                            UniqueName="WONo"  Visible="False"/>
                          <telerik:TreeListBoundColumn DataField="PId" HeaderText="Parent Node" 
                            UniqueName="PId" Visible="False"/>
                            <telerik:TreeListTemplateColumn HeaderText="Item Id"  Visible="false" 
                            UniqueName="ItemId"  >
                               
                            <ItemTemplate>
                               <asp:Label ID="lblItemId" runat="server" Text='<%# Eval("ItemId") %>'></asp:Label>
                            </ItemTemplate>
                                <HeaderStyle HorizontalAlign="Center" Width="60px" />
                            <ItemStyle Width="10%" HorizontalAlign="Center" />                            
                           </telerik:TreeListTemplateColumn>                            
                            <telerik:TreeListBoundColumn DataField="Unit Qty" HeaderText="Quantity" 
                            UniqueName="Unit Qty"  Visible="False"/>
                         
                            
                             <telerik:TreeListTemplateColumn HeaderStyle-Width="80px">                                
                                <ItemTemplate>
                                
                                   <telerik:RadButton ID="SelectButton" runat="server" Text="" CommandName="Select" Width="16px" Height="16px">
                                  <Image ImageUrl="../../../images/export.ico" />
                                  
                                  </telerik:RadButton>
                                   
                                </ItemTemplate>
                                
                                <HeaderStyle Width="10%" />
                          
                            </telerik:TreeListTemplateColumn>                           
                                                        
                            
                             <telerik:TreeListTemplateColumn HeaderStyle-Width="8%" ItemStyle-HorizontalAlign="Center" HeaderStyle-HorizontalAlign="Center" HeaderText="Drw/Image">  
                            
                                                        <ItemTemplate >
                                                            
                                                                
                                                            <asp:LinkButton ID="btnlnkImg" CommandName="downloadImg" Visible="true"  Text='<%# Bind("FileName") %>' runat="server"></asp:LinkButton>
                                                            
                                                        </ItemTemplate>
                                                      
                                                       
                                                        <HeaderStyle HorizontalAlign="Center" Width="8%" />
                                                        <ItemStyle HorizontalAlign="Center" />
                                                      
                                                       
                                                </telerik:TreeListTemplateColumn>                                               
                                                
                                               
                                                 <telerik:TreeListTemplateColumn  HeaderText="Spec. Sheet" HeaderStyle-Width="8%" ItemStyle-HorizontalAlign="Center" HeaderStyle-HorizontalAlign="Center">  
                                                    <ItemTemplate>
                                                        <asp:LinkButton ID="btnlnkSpec" CommandName="downloadSpec" Visible="true"  Text='<%# Bind("AttName") %>'  runat="server"></asp:LinkButton>
                          
                                                               
                                                    </ItemTemplate>                                                  
                                                   
                                                     <HeaderStyle HorizontalAlign="Center" Width="8%" />
                                                     <ItemStyle HorizontalAlign="Center" />
                                                   
                                               </telerik:TreeListTemplateColumn>
                                               
                                               <telerik:TreeListTemplateColumn HeaderText="Entry Date"  Visible="true" UniqueName="Entry Date"  > 
                               <ItemTemplate>
                                   <asp:Label ID="Label1" runat="server" Text='<%# Eval("EntryDate") %>'></asp:Label>                                   
                               </ItemTemplate>
                               <HeaderStyle HorizontalAlign="Center" Width="7%" />
                               <ItemStyle Width="7%" HorizontalAlign="Center" />
                        
                            </telerik:TreeListTemplateColumn> 
                                                                  
            </Columns>
            <PagerStyle CssClass="fontcss" />
            
            <HeaderStyle Font-Bold="True" CssClass="fontcss" />
            
            <SelectedItemStyle CssClass="fontcss" />
            
            <PagerTemplate>
                <table width="100%">
                    <tr>
                        <td align="center" width="7%">
<asp:Button ID="btnPageFirst" runat="server" Text=" " CssClass="rtlPageFirst" CommandName="Page"
CommandArgument="First" />
<asp:Button ID="btnPagePrev" runat="server" Text=" " CssClass="rtlPagePrev" CommandName="Page"
CommandArgument="Prev" /> 
                        </td>
                        <td align="center" width="4%">
                        <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                        </td>
                        <td align="center" width="6%">
                        <asp:Panel runat="server" ID="TreeListPagerPlaceHolder" />
<asp:Button ID="btnPageNext" runat="server" Text=" " CssClass="rtlPageNext" CommandName="Page"
CommandArgument="Next" />
<asp:Button ID="btnPageLast" runat="server" Text=" " CssClass="rtlPageLast" CommandName="Page"
CommandArgument="Last" />
<td>
    <asp:ImageButton ID="ImageButton1" runat="server" ImageUrl="../../../images/export.ico" OnClick="ImageButton1_Click" />
</td>

        </td>
        <td align="right">
                Displaying page
                <%# (int)DataBinder.Eval(Container, "Paging.CurrentPageIndex") + 1 %>
                of
                <%# (int)DataBinder.Eval(Container, "Paging.PageCount") %>
                / Items
                <%# (int)DataBinder.Eval(Container, "Paging.FirstIndexInPage") + 1 %>
                to
                <%# (int)DataBinder.Eval(Container, "Paging.LastIndexInPage") + 1 %>
                of
                <%# DataBinder.Eval(Container, "Paging.DataSourceCount")%>
        </td>
                    </tr>
                </table>
            </PagerTemplate>
            
        </telerik:RadTreeList>  
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
        
     </telerik:RadAjaxPanel>
    </td>
</tr>  
    </table>
</asp:Content>
<asp:Content ID="Content8" ContentPlaceHolderID="ContentPlaceHolder4" Runat="Server">
</asp:Content>

