# Generated by Django 5.2.7 on 2025-11-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblmisBudgetcode',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('symbol', models.TextField(blank=True, db_column='Symbol', null=True)),
            ],
            options={
                'verbose_name': 'Budget Code',
                'verbose_name_plural': 'Budget Codes',
                'db_table': 'tblMIS_BudgetCode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblmisBudgetcodeTime',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('symbol', models.TextField(blank=True, db_column='Symbol', null=True)),
            ],
            options={
                'verbose_name': 'Budget Code Time',
                'verbose_name_plural': 'Budget Codes Time',
                'db_table': 'tblMIS_BudgetCode_Time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblmisBudgethrsFieldCategory',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True, db_column='Category', null=True)),
                ('symbol', models.TextField(blank=True, db_column='Symbol', null=True)),
            ],
            options={
                'verbose_name': 'Budget Hours Field Category',
                'verbose_name_plural': 'Budget Hours Field Categories',
                'db_table': 'tblMIS_BudgetHrs_Field_Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblmisBudgethrsFieldSubcategory',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('subcategory', models.TextField(blank=True, db_column='SubCategory', null=True)),
                ('symbol', models.TextField(blank=True, db_column='Symbol', null=True)),
            ],
            options={
                'verbose_name': 'Budget Hours Field Sub-Category',
                'verbose_name_plural': 'Budget Hours Field Sub-Categories',
                'db_table': 'tblMIS_BudgetHrs_Field_SubCategory',
                'managed': False,
            },
        ),
    ]
