"""
Material Requisition Slip (MRS) Views
"""
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView, FormView, View
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q, Sum
from django.http import HttpResponse

# Import core mixins instead of inventory-specific mixins
from core.mixins import (
    BaseListViewMixin,
    BaseCreateViewMixin,
    BaseUpdateViewMixin,
    BaseDeleteViewMixin,
    BaseDetailViewMixin,
    LoginRequiredMixin,
    CompanyFinancialYearMixin,
    HTMXResponseMixin,
    QueryOptimizationMixin,
)

from ..models import (
    TblGatepass,
    TblinvMaterialrequisitionMaster, TblinvMaterialrequisitionDetails,
    TblinvMaterialissueMaster, TblinvMaterialissueDetails,
    TblinvMaterialreturnMaster, TblinvMaterialreturnDetails,
    TblinvInwardMaster, TblinvInwardDetails,
    TblinvMaterialreceivedMaster, TblinvMaterialreceivedDetails,
    TblinvMaterialservicenoteMaster, TblinvMaterialservicenoteDetails,
    TblinvSupplierChallanMaster, TblinvSupplierChallanDetails,
    TblinvCustomerChallanMaster, TblinvCustomerChallanDetails,
    TblinvWisMaster, TblinvWisDetails,
    TblvehProcessMaster,
    TblinvAutowisTimeschedule,
)
from .. import forms
from ..forms import (
    MRSMasterForm,
    MINMasterForm,
    MRNMasterForm,
    VehicleProcessMasterForm,
    VehicleMasterForm,
    AutoWISTimeScheduleForm,
    StockLedgerFilterForm,
)
from ..services import (
    MaterialRequisitionService,
    MaterialIssueService,
    MaterialReturnService,
    DashboardService,
)


class MRSListView(BaseListViewMixin, ListView):
    """
    Material Requisition Slip List View
    Displays all MRS with search and filter.

    Converted from: aspnet/Module/Inventory/Transactions/MaterialRequisitionSlip_MRS_New.aspx
    Optimized: Uses BaseListViewMixin with built-in search, pagination, and query optimization.
    Requirements: 3.1, 3.4, 4.1, 5.5, 13.1
    """
    model = TblinvMaterialrequisitionMaster
    template_name = 'inventory/transactions/mrs_list.html'
    partial_template_name = 'inventory/transactions/partials/mrs_list_partial.html'
    context_object_name = 'mrs_list'
    paginate_by = 20
    search_fields = ['mrsno']
    ordering = ['-id']

    def get_queryset(self):
        """Override to add financial year display and generated by name."""
        queryset = super().get_queryset()

        # Import here to avoid circular imports
        from sys_admin.models import TblfinancialMaster
        from django.contrib.auth.models import User

        # Annotate each MRS with financial year display
        for mrs in queryset:
            # Get financial year display
            try:
                fin_year = TblfinancialMaster.objects.get(finyearid=mrs.finyearid)
                mrs.finyear_display = fin_year.finyear
            except TblfinancialMaster.DoesNotExist:
                mrs.finyear_display = f"FY-{mrs.finyearid}"

            # Get user name from sessionid
            try:
                user = User.objects.get(id=mrs.sessionid)
                mrs.generated_by_name = f"Mr.{user.get_full_name() or user.username}".upper()
            except (User.DoesNotExist, ValueError):
                mrs.generated_by_name = f"User-{mrs.sessionid}"

        return queryset



class MRSCreateView(LoginRequiredMixin, CompanyFinancialYearMixin, TemplateView):
    """
    Material Requisition Slip Create View
    Two-tab interface: Item Master + Selected Items
    Uses session-based cart matching ASP.NET workflow

    Requirements: 3.1, 3.2, 4.1, 4.2, 13.2
    """
    template_name = 'inventory/transactions/mrs_form.html'

    def get_context_data(self, **kwargs):
        """Provide context for MRS form with categories, departments, and cart items."""
        from design.models import TbldgCategoryMaster
        from human_resource.models import Businessgroup

        context = super().get_context_data(**kwargs)

        # Get categories for dropdown
        context['categories'] = TbldgCategoryMaster.objects.filter(
            compid=self.get_compid()
        ).values('cid', 'symbol').order_by('symbol')

        # Get departments for BGGroup dropdown
        context['departments'] = list(Businessgroup.objects.all().values('id', 'symbol'))

        # Get cart items from session
        context['cart_items'] = self.request.session.get('mrs_cart', [])

        # No items initially - loaded via HTMX search
        context['items'] = []

        return context

    def post(self, request, *args, **kwargs):
        """Generate MRS from cart items."""
        from django.db import transaction
        from datetime import datetime

        # Get cart items from session
        cart_items = request.session.get('mrs_cart', [])

        if not cart_items:
            messages.error(request, 'Please add at least one item to cart!')
            return redirect('inventory:mrs-create')

        # Generate MRS number
        mrsno = MaterialRequisitionService.generate_mrs_number(
            self.get_compid(),
            self.get_finyearid()
        )

        # Save master and details in atomic transaction
        with transaction.atomic():
            # Create MRS master
            mrs_master = TblinvMaterialrequisitionMaster()
            mrs_master.mrsno = mrsno
            mrs_master.sysdate = datetime.now().strftime('%d-%m-%Y')
            mrs_master.systime = datetime.now().strftime('%H:%M:%S')
            mrs_master.compid = self.get_compid()
            mrs_master.finyearid = self.get_finyearid()
            mrs_master.sessionid = str(request.user.id)
            mrs_master.save()

            # Create MRS details for each cart item
            for item in cart_items:
                detail = TblinvMaterialrequisitionDetails()
                detail.mid = mrs_master.id
                detail.mrsno = mrsno
                detail.itemid = item.get('item_id')
                detail.reqqty = float(item.get('req_qty', 0))
                detail.remarks = item.get('remarks', '')

                # Set either deptid or wono
                if item.get('dept_id'):
                    detail.deptid = int(item.get('dept_id'))
                    detail.wono = None
                else:
                    detail.wono = item.get('wono', '')
                    detail.deptid = None

                detail.save()

            # Clear cart
            request.session['mrs_cart'] = []
            request.session.modified = True

        messages.success(request, f'Material Requisition {mrsno} created successfully!')
        return redirect('inventory:mrs-list')


class MRSSearchItemsView(LoginRequiredMixin, CompanyFinancialYearMixin, TemplateView):
    """
    HTMX endpoint to search items by category/description/location
    Returns partial HTML for items grid
    """
    template_name = 'inventory/transactions/partials/mrs_items_grid.html'

    def get_context_data(self, **kwargs):
        from design.models import TbldgItemMaster
        from human_resource.models import Businessgroup

        context = super().get_context_data(**kwargs)

        # Get search parameters
        category_id = self.request.GET.get('category-select', '')
        search_type = self.request.GET.get('search-type', 'itemcode')
        search_text = self.request.GET.get('search-text', '').strip()

        # Base query
        items = TbldgItemMaster.objects.filter(compid=self.get_compid())

        # Filter by category if provided
        if category_id:
            items = items.filter(cid=category_id)

        # Filter by search type and text
        if search_text:
            if search_type == 'itemcode':
                items = items.filter(itemcode__icontains=search_text)
            elif search_type == 'description':
                items = items.filter(manfdesc__icontains=search_text)
            elif search_type == 'location':
                items = items.filter(location__icontains=search_text)

        # Limit results and get values
        context['items'] = items.values(
            'id', 'itemcode', 'manfdesc', 'uombasic', 'stockqty', 'location'
        ).order_by('itemcode')[:50]

        # Get departments for dropdown in each row
        context['departments'] = list(Businessgroup.objects.all().values('id', 'symbol'))

        return context


class MRSAddToCartView(LoginRequiredMixin, View):
    """
    HTMX endpoint to add item to session cart
    Returns updated cart grid
    """
    def post(self, request, *args, **kwargs):
        from human_resource.models import Businessgroup

        # Get item data from POST
        item_data = {
            'item_id': request.POST.get('item_id'),
            'item_code': request.POST.get('item_code'),
            'item_desc': request.POST.get('item_desc'),
            'uom': request.POST.get('uom'),
            'stock_qty': request.POST.get('stock_qty'),
            'req_qty': request.POST.get('req_qty'),
            'type': request.POST.get('type'),
            'dept_id': request.POST.get('dept_id'),
            'wono': request.POST.get('wono'),
            'remarks': request.POST.get('remarks'),
            'location': request.POST.get('location'),
        }

        # Validate required fields
        if not item_data['req_qty'] or float(item_data['req_qty']) <= 0:
            return HttpResponse('Please enter a valid quantity', status=400)

        if item_data['type'] == 'bggroup' and not item_data['dept_id']:
            return HttpResponse('Please select a department', status=400)

        if item_data['type'] == 'wono' and not item_data['wono']:
            return HttpResponse('Please enter a work order number', status=400)

        # Get department name if dept_id provided
        if item_data['dept_id']:
            try:
                dept = Businessgroup.objects.get(id=item_data['dept_id'])
                item_data['dept_name'] = dept.symbol
            except Businessgroup.DoesNotExist:
                item_data['dept_name'] = item_data['dept_id']

        # Add to session cart
        cart = request.session.get('mrs_cart', [])
        cart.append(item_data)
        request.session['mrs_cart'] = cart
        request.session.modified = True

        # Return updated cart grid
        context = {'cart_items': cart}
        return render(request, 'inventory/transactions/partials/mrs_cart_grid.html', context)


class MRSRemoveFromCartView(LoginRequiredMixin, View):
    """
    HTMX endpoint to remove item from session cart
    Returns updated cart grid
    """
    def post(self, request, *args, **kwargs):
        # Get item index from POST
        item_index = int(request.POST.get('item_index', -1))

        # Remove from session cart
        cart = request.session.get('mrs_cart', [])
        if 0 <= item_index < len(cart):
            cart.pop(item_index)
            request.session['mrs_cart'] = cart
            request.session.modified = True

        # Return updated cart grid
        context = {'cart_items': cart}
        return render(request, 'inventory/transactions/partials/mrs_cart_grid.html', context)


class MRSDetailView(BaseDetailViewMixin, DetailView):
    """
    Material Requisition Slip Detail View
    Display MRS details with line items.
    
    Optimized: Uses BaseDetailViewMixin with automatic company filtering.
    Requirements: 3.1, 4.1, 13.1
    """
    model = TblinvMaterialrequisitionMaster
    template_name = 'inventory/transactions/mrs_detail.html'
    context_object_name = 'mrs'
    
    # No need to override get_queryset() - BaseDetailViewMixin handles company filtering
    
    def get_context_data(self, **kwargs):
        """Add MRS detail lines to context."""
        context = super().get_context_data(**kwargs)
        context['details'] = TblinvMaterialrequisitionDetails.objects.filter(
            mid=self.object.id
        )
        return context



class MRSDeleteView(BaseDeleteViewMixin, DeleteView):
    """
    Material Requisition Slip Delete View
    Delete MRS if not issued.
    
    Optimized: Uses BaseDeleteViewMixin with automatic HTMX support.
    Requirements: 3.1, 4.1, 13.2
    """
    model = TblinvMaterialrequisitionMaster
    template_name = 'inventory/transactions/mrs_confirm_delete.html'
    success_url = reverse_lazy('inventory:mrs-list')
    
    # No need to override get_queryset() - BaseDeleteViewMixin handles company filtering
    
    def delete(self, request, *args, **kwargs):
        """Delete with validation - check if MRS has been issued."""
        self.object = self.get_object()
        
        # Check if MRS has been issued
        issued_qty = TblinvMaterialissueDetails.objects.filter(
            mid__mrsid=self.object.id
        ).aggregate(total=Sum('issueqty'))['total'] or 0
        
        if issued_qty > 0:
            messages.error(request, 'Cannot delete MRS that has been issued!')
            if request.headers.get('HX-Request'):
                return HttpResponse(status=409, reason="MRS has been issued")
            return redirect('inventory:mrs-detail', pk=self.object.pk)
        
        mrsno = self.object.mrsno
        messages.success(request, f'Material Requisition {mrsno} deleted successfully!')
        return super().delete(request, *args, **kwargs)



class MRSPrintView(BaseDetailViewMixin, DetailView):
    """
    Material Requisition Slip Print View
    Print-friendly MRS document.
    
    Optimized: Uses BaseDetailViewMixin with automatic company filtering.
    Requirements: 3.1, 4.1
    """
    model = TblinvMaterialrequisitionMaster
    template_name = 'inventory/transactions/mrs_print.html'
    context_object_name = 'mrs'
    
    # No need to override get_queryset() - BaseDetailViewMixin handles company filtering
    
    def get_context_data(self, **kwargs):
        """Add MRS detail lines to context."""
        context = super().get_context_data(**kwargs)
        context['details'] = TblinvMaterialrequisitionDetails.objects.filter(
            mid=self.object.id
        )
        return context



class MRSPendingListView(LoginRequiredMixin, CompanyFinancialYearMixin, TemplateView):
    """
    Pending MRS List View for Material Issue
    Shows MRS with balance quantities.
    
    Converted from: aspnet/Module/Inventory/Transactions/MaterialIssueNote_MIN_New.aspx
    Optimized: Uses core mixins instead of InventoryBaseMixin.
    Requirements: 3.1, 4.1, 4.2
    """
    template_name = 'inventory/transactions/mrs_pending_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Get pending MRS
        context['pending_mrs'] = MaterialRequisitionService.get_pending_mrs_for_issue(
            self.get_compid(),
            self.get_finyearid()
        )
        
        return context



