# Generated by Django 5.2.7 on 2025-11-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblcity',
            fields=[
                ('cityid', models.AutoField(db_column='CityId', primary_key=True, serialize=False)),
                ('cityname', models.TextField(blank=True, db_column='CityName', null=True)),
            ],
            options={
                'db_table': 'tblCity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblcompanyMaster',
            fields=[
                ('compid', models.AutoField(db_column='CompId', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(db_column='SysDate', max_length=50)),
                ('systime', models.CharField(db_column='SysTime', max_length=50)),
                ('companyname', models.TextField(db_column='CompanyName')),
                ('regdaddress', models.TextField(blank=True, db_column='RegdAddress', null=True)),
                ('regdstate', models.IntegerField(db_column='RegdState')),
                ('regdcountry', models.IntegerField(db_column='RegdCountry')),
                ('regdpincode', models.TextField(blank=True, db_column='RegdPinCode', null=True)),
                ('regdcontactno', models.TextField(blank=True, db_column='RegdContactNo', null=True)),
                ('regdfaxno', models.TextField(blank=True, db_column='RegdFaxNo', null=True)),
                ('regdemail', models.TextField(blank=True, db_column='RegdEmail', null=True)),
                ('plantaddress', models.TextField(blank=True, db_column='PlantAddress', null=True)),
                ('plantstate', models.IntegerField(db_column='PlantState')),
                ('plantcountry', models.IntegerField(db_column='PlantCountry')),
                ('plantpincode', models.TextField(blank=True, db_column='PlantPinCode', null=True)),
                ('plantcontactno', models.TextField(blank=True, db_column='PlantContactNo', null=True)),
                ('plantfaxno', models.TextField(blank=True, db_column='PlantFaxNo', null=True)),
                ('plantemail', models.TextField(blank=True, db_column='PlantEmail', null=True)),
                ('eccno', models.TextField(blank=True, db_column='ECCNo', null=True)),
                ('commissionerate', models.TextField(blank=True, db_column='Commissionerate', null=True)),
                ('range', models.TextField(blank=True, db_column='Range', null=True)),
                ('division', models.TextField(blank=True, db_column='Division', null=True)),
                ('locationno', models.TextField(blank=True, db_column='LocationNo', null=True)),
                ('vat', models.TextField(blank=True, db_column='VAT', null=True)),
                ('cstno', models.TextField(blank=True, db_column='CSTNo', null=True)),
                ('panno', models.TextField(blank=True, db_column='PANNo', null=True)),
                ('logoimage', models.BinaryField(blank=True, db_column='LogoImage', null=True)),
                ('logofilename', models.TextField(blank=True, db_column='LogoFileName', null=True)),
                ('prefix', models.TextField(blank=True, db_column='Prefix', null=True)),
                ('licencenos', models.TextField(blank=True, db_column='LicenceNos', null=True)),
                ('defaultcomp', models.IntegerField(blank=True, db_column='DefaultComp', null=True)),
                ('mailserverip', models.TextField(blank=True, db_column='MailServerIp', null=True)),
                ('serverip', models.TextField(blank=True, db_column='ServerIp', null=True)),
                ('flag', models.IntegerField(blank=True, db_column='Flag', null=True)),
                ('itemcodelimit', models.IntegerField(blank=True, db_column='ItemCodeLimit', null=True)),
                ('erpsysmail', models.TextField(blank=True, db_column='ErpSysmail', null=True)),
                ('mobileno', models.TextField(blank=True, db_column='MobileNo', null=True)),
                ('password', models.TextField(blank=True, db_column='Password', null=True)),
            ],
            options={
                'db_table': 'tblCompany_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcountry',
            fields=[
                ('cid', models.AutoField(db_column='CId', primary_key=True, serialize=False)),
                ('countryname', models.TextField(blank=True, db_column='CountryName', null=True)),
                ('currency', models.TextField(blank=True, db_column='Currency', null=True)),
                ('symbol', models.TextField(blank=True, db_column='Symbol', null=True)),
                ('keyshortcut', models.TextField(blank=True, db_column='KeyShortcut', null=True)),
            ],
            options={
                'db_table': 'tblCountry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblexciseserMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('terms', models.TextField(blank=True, db_column='Terms', null=True)),
                ('value', models.FloatField(blank=True, db_column='Value', null=True)),
                ('accessablevalue', models.FloatField(blank=True, db_column='AccessableValue', null=True)),
                ('educess', models.FloatField(blank=True, db_column='EDUCess', null=True)),
                ('shecess', models.FloatField(blank=True, db_column='SHECess', null=True)),
                ('live', models.IntegerField(blank=True, db_column='Live', null=True)),
                ('livesertax', models.IntegerField(blank=True, db_column='LiveSerTax', null=True)),
            ],
            options={
                'db_table': 'tblExciseser_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblfinancialMaster',
            fields=[
                ('finyearid', models.AutoField(db_column='FinYearId', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(db_column='SysDate', max_length=50)),
                ('systime', models.CharField(db_column='SysTime', max_length=50)),
                ('sessionid', models.TextField(db_column='SessionId')),
                ('compid', models.IntegerField(db_column='CompId')),
                ('finyearfrom', models.CharField(blank=True, db_column='FinYearFrom', max_length=50, null=True)),
                ('finyearto', models.CharField(blank=True, db_column='FinYearTo', max_length=50, null=True)),
                ('finyear', models.CharField(blank=True, db_column='FinYear', max_length=50, null=True)),
                ('flag', models.IntegerField(blank=True, db_column='Flag', null=True)),
            ],
            options={
                'db_table': 'tblFinancial_master',
                'ordering': ['-finyearfrom'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblgstMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('gstrate', models.TextField(blank=True, db_column='GSTRate', null=True)),
                ('ratevalue', models.FloatField(blank=True, db_column='RateValue', null=True)),
                ('cgstrate', models.FloatField(blank=True, db_column='CGSTRate', null=True)),
                ('sgstrate', models.FloatField(blank=True, db_column='SGSTRate', null=True)),
                ('igstrate', models.FloatField(blank=True, db_column='IGSTRate', null=True)),
                ('hsnapplicable', models.TextField(blank=True, db_column='HSNApplicable', null=True)),
                ('live', models.IntegerField(db_column='Live', default=1)),
                ('effectivefrom', models.TextField(blank=True, db_column='EffectiveFrom', null=True)),
            ],
            options={
                'db_table': 'tblGST_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblstate',
            fields=[
                ('sid', models.AutoField(db_column='SId', primary_key=True, serialize=False)),
                ('statename', models.TextField(blank=True, db_column='StateName', null=True)),
            ],
            options={
                'db_table': 'tblState',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblvatMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('terms', models.TextField(blank=True, db_column='Terms', null=True)),
                ('value', models.FloatField(blank=True, db_column='Value', null=True)),
                ('live', models.IntegerField(blank=True, db_column='Live', null=True)),
                ('isvat', models.IntegerField(db_column='IsVAT', default=1)),
                ('iscst', models.IntegerField(db_column='IsCST', default=1)),
            ],
            options={
                'db_table': 'tblVAT_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('unitname', models.TextField(blank=True, db_column='UnitName', null=True)),
                ('symbol', models.TextField(blank=True, db_column='Symbol', null=True)),
                ('effectoninvoice', models.IntegerField(blank=True, db_column='EffectOnInvoice', null=True)),
            ],
            options={
                'db_table': 'Unit_Master',
                'managed': False,
            },
        ),
    ]
