# Generated by Django 5.2.7 on 2025-11-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblmpMaterialDetail',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('item', models.IntegerField(blank=True, db_column='ItemId', null=True)),
                ('rm', models.IntegerField(blank=True, db_column='RM', null=True)),
                ('pro', models.IntegerField(blank=True, db_column='PRO', null=True)),
                ('fin', models.IntegerField(blank=True, db_column='FIN', null=True)),
            ],
            options={
                'db_table': 'tblMP_Material_Detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblmpMaterialFinish',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('item', models.IntegerField(blank=True, db_column='ItemId', null=True)),
                ('supplierid', models.TextField(db_column='SupplierId')),
                ('qty', models.FloatField(db_column='Qty')),
                ('rate', models.FloatField(db_column='Rate')),
                ('discount', models.FloatField(db_column='Discount')),
                ('deldate', models.TextField(db_column='DelDate')),
            ],
            options={
                'db_table': 'tblMP_Material_Finish',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblmpMaterialMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sysdate', models.CharField(blank=True, db_column='SysDate', max_length=50, null=True)),
                ('systime', models.CharField(blank=True, db_column='SysTime', max_length=50, null=True)),
                ('compid', models.IntegerField(db_column='CompId')),
                ('sessionid', models.TextField(blank=True, db_column='SessionId', null=True)),
                ('finyearid', models.IntegerField(db_column='FinYearId')),
                ('plno', models.TextField(db_column='PLNo')),
                ('wono', models.TextField(db_column='WONo')),
                ('supplierid', models.TextField(blank=True, db_column='SupplierId', null=True)),
                ('compdate', models.CharField(blank=True, db_column='CompDate', max_length=50, null=True)),
                ('pid', models.IntegerField(blank=True, db_column='PId', null=True)),
                ('cid', models.IntegerField(blank=True, db_column='CId', null=True)),
                ('itemid', models.IntegerField(blank=True, db_column='ItemId', null=True)),
            ],
            options={
                'db_table': 'tblMP_Material_Master',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblmpMaterialProcess',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('plno', models.TextField(blank=True, db_column='PLNo', null=True)),
                ('mid', models.IntegerField(blank=True, db_column='MId', null=True)),
                ('item', models.IntegerField(blank=True, db_column='ItemId', null=True)),
                ('supplierid', models.TextField(blank=True, db_column='SupplierId', null=True)),
                ('compdate', models.CharField(blank=True, db_column='CompDate', max_length=50, null=True)),
                ('pid', models.IntegerField(blank=True, db_column='PId', null=True)),
                ('cid', models.IntegerField(blank=True, db_column='CId', null=True)),
                ('qty', models.FloatField(blank=True, db_column='Qty', null=True)),
                ('rate', models.FloatField(blank=True, db_column='Rate', null=True)),
                ('discount', models.FloatField(blank=True, db_column='Discount', default=0, null=True)),
                ('deldate', models.TextField(blank=True, db_column='DelDate', null=True)),
            ],
            options={
                'db_table': 'tblMP_Material_Process',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblmpMaterialRawmaterial',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('plno', models.TextField(blank=True, db_column='PLNo', null=True)),
                ('mid', models.IntegerField(blank=True, db_column='MId', null=True)),
                ('item', models.IntegerField(blank=True, db_column='ItemId', null=True)),
                ('supplierid', models.TextField(blank=True, db_column='SupplierId', null=True)),
                ('compdate', models.CharField(blank=True, db_column='CompDate', max_length=50, null=True)),
                ('pid', models.IntegerField(blank=True, db_column='PId', null=True)),
                ('cid', models.IntegerField(blank=True, db_column='CId', null=True)),
                ('qty', models.FloatField(blank=True, db_column='Qty', null=True)),
                ('rate', models.FloatField(blank=True, db_column='Rate', null=True)),
                ('discount', models.FloatField(blank=True, db_column='Discount', default=0, null=True)),
                ('deldate', models.TextField(blank=True, db_column='DelDate', null=True)),
            ],
            options={
                'db_table': 'tblMP_Material_RawMaterial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblplnProcessMaster',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('processname', models.TextField(blank=True, db_column='ProcessName', null=True)),
                ('symbol', models.TextField(blank=True, db_column='Symbol', null=True)),
            ],
            options={
                'db_table': 'tblPln_Process_Master',
                'managed': False,
            },
        ),
    ]
