"""
Material Management PO Views

Converted from: aspnet/Module/MaterialManagement/
Following Django conventions, HTMX patterns, and Tailwind standards
"""

from datetime import datetime

from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView, View
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.db.models import Q, Max

from core.mixins import HTMXResponseMixin
from .dashboard import MaterialManagementBaseMixin
from ..models import POMaster, PODetails, PRMaster, PRDetails, SPRMaster, SPRDetails, MmPrPoTemp, MmSprPoTemp, Supplier


class POListView(MaterialManagementBaseMixin, ListView):
    """Purchase Order List"""
    model = POMaster
    template_name = 'material_management/transactions/po_list.html'
    context_object_name = 'pos'
    paginate_by = 20

    def get_queryset(self):
        # Filter by company (always required)
        qs = super().get_queryset().filter(
            comp_id=self.get_compid()
        )

        # Filter by financial year only if explicitly set in session
        # When "All Years" is selected, finyearid will be None or not in session
        fin_year_id = self.request.session.get('finyearid')
        if fin_year_id:
            qs = qs.filter(fin_year_id__lte=fin_year_id)

        # Order by newest first
        qs = qs.order_by('-po_id')

        # Search functionality
        search_query = self.request.GET.get('search', '').strip()
        if search_query:
            qs = qs.filter(
                Q(po_no__icontains=search_query) |
                Q(supplier_id__icontains=search_query)
            )

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('search', '')

        # Add supplier names and usernames to each PO
        from .models import Supplier
        from django.contrib.auth import get_user_model
        User = get_user_model()

        for po in context['pos']:
            # Add supplier name
            if po.supplier_id:
                try:
                    supplier = Supplier.objects.get(supplier_id=po.supplier_id)
                    po.supplier_name = supplier.supplier_name
                except Supplier.DoesNotExist:
                    po.supplier_name = po.supplier_id
            else:
                po.supplier_name = '-'

            # Add username for "Generated By"
            if po.session_id:
                try:
                    user = User.objects.get(id=int(po.session_id))
                    po.generated_by = user.username
                except (User.DoesNotExist, ValueError):
                    po.generated_by = po.session_id
            else:
                po.generated_by = '-'

        return context




class PONewView(MaterialManagementBaseMixin, TemplateView):
    """
    PO Step 1: Supplier Selection (with PR/SPR tabs)

    Shows suppliers who have pending PR or SPR items not fully converted to PO.
    User selects supplier to proceed to item selection.

    Converted from: aaspnet/MaterialManagement/Transactions/PO_New.aspx
    """
    template_name = 'material_management/transactions/po_new.html'

    def get(self, request, *args, **kwargs):
        # Clear temporary tables for this user session on initial load
        comp_id = self.get_compid()
        session_id = str(request.user.id)

        MmPrPoTemp.objects.filter(comp_id=comp_id, session_id=session_id).delete()
        MmSprPoTemp.objects.filter(comp_id=comp_id, session_id=session_id).delete()

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Default to PR tab
        active_tab = self.request.GET.get('tab', 'pr')
        context['active_tab'] = active_tab

        # Get suppliers with pending items based on tab
        if active_tab == 'spr':
            context['suppliers'] = self.get_spr_suppliers()
        else:
            context['suppliers'] = self.get_pr_suppliers()

        context['search_query'] = self.request.GET.get('search', '')

        return context

    def get_pr_suppliers(self):
        """
        Get suppliers who have PR items with remaining quantity (PRQty > POQty)
        Matches: GetSupplier_PO_PR stored procedure
        """
        from .po_services import POSupplierService

        comp_id = self.get_compid()
        fin_year_id = self.get_finyearid()
        search_query = self.request.GET.get('search', '').strip()

        supplier_code = None
        if search_query:
            # Extract code from search like "Supplier Name [CODE]"
            if '[' in search_query and ']' in search_query:
                supplier_code = search_query.split('[')[-1].replace(']', '').strip()
            else:
                supplier_code = search_query

        suppliers = POSupplierService.get_suppliers_with_pr_items(
            comp_id, fin_year_id, supplier_code
        )

        return suppliers

    def get_spr_suppliers(self):
        """
        Get suppliers who have SPR items with remaining quantity (SPRQty > POQty)
        Matches: GetSupplier_PO_SPR stored procedure
        """
        from .po_services import POSupplierService

        comp_id = self.get_compid()
        fin_year_id = self.get_finyearid()
        search_query = self.request.GET.get('search', '').strip()

        supplier_code = None
        if search_query:
            if '[' in search_query and ']' in search_query:
                supplier_code = search_query.split('[')[-1].replace(']', '').strip()
            else:
                supplier_code = search_query

        suppliers = POSupplierService.get_suppliers_with_spr_items(
            comp_id, fin_year_id, supplier_code
        )

        return suppliers




class POPRItemsView(MaterialManagementBaseMixin, TemplateView):
    """
    PO Step 2: PR Item Grid (for selected supplier)

    Shows all pending PR items for the selected supplier.
    User can select items to add to PO.

    Converted from: aaspnet/MaterialManagement/Transactions/PO_PR_Items.aspx
                   aaspnet/MaterialManagement/Transactions/PO_PR_ItemGrid.aspx
    """
    template_name = 'material_management/transactions/po_pr_items.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        supplier_code = self.kwargs.get('supplier_code')

        # Get supplier details
        from .models import Supplier
        try:
            supplier = Supplier.objects.get(supplier_id=supplier_code, comp_id=self.get_compid())
            context['supplier'] = supplier
        except Supplier.DoesNotExist:
            context['supplier'] = None

        # Get pending PR items for this supplier
        context['pr_items'] = self.get_pr_items(supplier_code)
        context['supplier_code'] = supplier_code

        return context

    def get_pr_items(self, supplier_code):
        """
        Get all PR items for supplier that have remaining quantity
        Matches the ItemGrid logic from ASP.NET
        """
        from django.db.models import Sum, F, Q, Case, When, Value, DecimalField
        from .models import PRMaster, PRDetails, PODetails
        from design.models import TbldgItemMaster

        comp_id = self.get_compid()
        fin_year_id = self.get_finyearid()

        # Get PR master records for this company and financial year
        pr_masters = PRMaster.objects.filter(
            comp_id=comp_id,
            fin_year_id__lte=fin_year_id
        ).values_list('pr_id', flat=True)

        # Get PR details for this supplier
        pr_items = PRDetails.objects.filter(
            supplier_id=supplier_code,
            m_id__in=pr_masters
        )

        # Calculate remaining quantity for each item
        items_with_remain = []
        for pr_item in pr_items:
            # Calculate total PO qty for this PR detail
            po_qty = PODetails.objects.filter(
                pr_id=pr_item.id
            ).aggregate(total=Sum('qty'))['total'] or 0

            remain_qty = float(pr_item.qty) - float(po_qty)

            if remain_qty > 0:
                # Add calculated fields to the object
                pr_item.po_qty = po_qty
                pr_item.remain_qty = remain_qty
                items_with_remain.append(pr_item)

        return items_with_remain




class POSPRItemsView(MaterialManagementBaseMixin, TemplateView):
    """
    PO Step 2: SPR Item Grid (for selected supplier)

    Shows all pending SPR items for the selected supplier.

    Converted from: aaspnet/MaterialManagement/Transactions/PO_SPR_Items.aspx
                   aaspnet/MaterialManagement/Transactions/PO_SPR_ItemGrid.aspx
    """
    template_name = 'material_management/transactions/po_spr_items.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        supplier_code = self.kwargs.get('supplier_code')

        # Get supplier details
        from .models import Supplier
        try:
            supplier = Supplier.objects.get(supplier_id=supplier_code, comp_id=self.get_compid())
            context['supplier'] = supplier
        except Supplier.DoesNotExist:
            context['supplier'] = None

        # Get pending SPR items for this supplier
        context['spr_items'] = self.get_spr_items(supplier_code)
        context['supplier_code'] = supplier_code

        return context

    def get_spr_items(self, supplier_code):
        """Get all SPR items for supplier that have remaining quantity"""
        from django.db.models import Sum, F, Q, Case, When, Value, DecimalField
        from .models import SPRMaster, SPRDetails, PODetails

        comp_id = self.get_compid()
        fin_year_id = self.get_finyearid()

        # Get SPR master records for this company and financial year
        spr_masters = SPRMaster.objects.filter(
            comp_id=comp_id,
            fin_year_id__lte=fin_year_id,
            authorize=1  # SPR requires authorization
        ).values_list('spr_id', flat=True)

        spr_items = SPRDetails.objects.filter(
            supplier_id=supplier_code,
            m_id__in=spr_masters
        )

        # Calculate remaining quantity for each item
        items_with_remain = []
        for spr_item in spr_items:
            # Calculate total PO qty for this SPR detail
            po_qty = PODetails.objects.filter(
                spr_id=spr_item.id
            ).aggregate(total=Sum('qty'))['total'] or 0

            remain_qty = float(spr_item.qty) - float(po_qty)

            if remain_qty > 0:
                # Add calculated fields to the object
                spr_item.po_qty = po_qty
                spr_item.remain_qty = remain_qty
                items_with_remain.append(spr_item)

        return items_with_remain




class POPRItemSelectView(MaterialManagementBaseMixin, View):
    """
    PO Step 3: Item Entry Form (for a specific PR item)

    User enters quantity, rate, discount, taxes for the selected item.
    Saves to temporary table tblMM_PR_Po_Temp.

    Converted from: aaspnet/MaterialManagement/Transactions/PO_PR_ItemSelect.aspx
    """
    template_name = 'material_management/transactions/po_item_select.html'

    def get(self, request, *args, **kwargs):
        pr_detail_id = kwargs.get('pr_detail_id')
        supplier_code = kwargs.get('supplier_code')

        # Get PR item details
        from .models import PRDetails, PRMaster, PODetails
        from design.models import TbldgItemMaster
        from django.db.models import Sum

        pr_item = get_object_or_404(PRDetails, id=pr_detail_id)

        # Manually fetch related PRMaster since m_id is IntegerField
        try:
            pr_master = PRMaster.objects.get(pr_id=pr_item.m_id)
        except PRMaster.DoesNotExist:
            pr_master = None

        # Manually fetch related Item since item_id is IntegerField
        try:
            item = TbldgItemMaster.objects.get(id=pr_item.item_id)
        except TbldgItemMaster.DoesNotExist:
            item = None

        # Calculate remaining quantity (already PO'd quantity)
        po_qty = PODetails.objects.filter(pr_id=pr_detail_id).aggregate(
            total=Sum('qty')
        )['total'] or 0

        remain_qty = float(pr_item.qty or 0) - float(po_qty)

        context = {
            'pr_item': pr_item,
            'pr_master': pr_master,
            'item': item,
            'remain_qty': remain_qty,
            'po_qty': po_qty,
            'supplier_code': supplier_code,
        }

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """Save item to temporary table"""
        from datetime import datetime
        from decimal import Decimal

        pr_detail_id = kwargs.get('pr_detail_id')
        supplier_code = kwargs.get('supplier_code')

        # Get form data
        qty = Decimal(request.POST.get('qty', 0))
        rate = Decimal(request.POST.get('rate', 0))
        discount = Decimal(request.POST.get('discount', 0))

        # Convert empty strings to None for optional integer fields
        pf_id = request.POST.get('pf_id') or None
        exst_id = request.POST.get('exst_id') or None
        vat_id = request.POST.get('vat_id') or None

        del_date = request.POST.get('del_date') or None
        remarks = request.POST.get('remarks', '')

        # Get PR item and related master
        from .models import PRDetails, PRMaster
        pr_item = get_object_or_404(PRDetails, id=pr_detail_id)

        # Get PR master to get PR number
        try:
            pr_master = PRMaster.objects.get(pr_id=pr_item.m_id)
            pr_no = pr_master.pr_no
        except PRMaster.DoesNotExist:
            pr_no = pr_item.pr_no  # Fallback to PR number from details

        # Calculate total amount
        from .po_services import POCalculationService
        total_amt = POCalculationService.calculate_total_amt(
            qty, rate, discount,
            pf_id or 0, exst_id or 0, vat_id or 0
        )

        # Save to temp table
        MmPrPoTemp.objects.create(
            pr_no=pr_no,
            pr_id=pr_detail_id,
            qty=qty,
            rate=rate,
            discount=discount,
            pf=pf_id,
            ex_st=exst_id,
            vat=vat_id,
            del_date=del_date,
            add_desc=remarks,
            session_id=str(request.user.id),
            comp_id=self.get_compid()
        )

        messages.success(request, 'Item added to PO successfully!')

        # Redirect back to item grid
        return redirect('material_management:po-pr-items', supplier_code=supplier_code)




class POSPRItemSelectView(MaterialManagementBaseMixin, View):
    """
    PO Step 3: Item Entry Form for SPR items
    Similar to POPRItemSelectView but for SPR
    """
    template_name = 'material_management/transactions/po_item_select.html'

    def get(self, request, *args, **kwargs):
        spr_detail_id = kwargs.get('spr_detail_id')
        supplier_code = kwargs.get('supplier_code')

        from .models import SPRDetails, SPRMaster, PODetails
        from design.models import TbldgItemMaster
        from django.db.models import Sum

        spr_item = get_object_or_404(SPRDetails, id=spr_detail_id)

        # Manually fetch related SPRMaster since m_id is IntegerField
        try:
            spr_master = SPRMaster.objects.get(spr_id=spr_item.m_id)
        except SPRMaster.DoesNotExist:
            spr_master = None

        # Manually fetch related Item since item_id is IntegerField
        try:
            spr_item_obj = TbldgItemMaster.objects.get(id=spr_item.item_id)
        except TbldgItemMaster.DoesNotExist:
            spr_item_obj = None

        # Calculate remaining quantity
        po_qty = PODetails.objects.filter(spr_id=spr_detail_id).aggregate(
            total=Sum('qty')
        )['total'] or 0

        remain_qty = float(spr_item.qty or 0) - float(po_qty)

        context = {
            'spr_item': spr_item,
            'spr_master': spr_master,
            'spr_item_obj': spr_item_obj,
            'remain_qty': remain_qty,
            'po_qty': po_qty,
            'supplier_code': supplier_code,
            'is_spr': True,
        }

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """Save SPR item to temporary table"""
        from datetime import datetime
        from decimal import Decimal

        spr_detail_id = kwargs.get('spr_detail_id')
        supplier_code = kwargs.get('supplier_code')

        qty = Decimal(request.POST.get('qty', 0))
        rate = Decimal(request.POST.get('rate', 0))
        discount = Decimal(request.POST.get('discount', 0))

        # Convert empty strings to None for optional integer fields
        pf_id = request.POST.get('pf_id') or None
        exst_id = request.POST.get('exst_id') or None
        vat_id = request.POST.get('vat_id') or None

        del_date = request.POST.get('del_date') or None
        remarks = request.POST.get('remarks', '')

        from .models import SPRDetails, SPRMaster
        spr_item = get_object_or_404(SPRDetails, id=spr_detail_id)

        # Get SPR master to get SPR number
        try:
            spr_master = SPRMaster.objects.get(spr_id=spr_item.m_id)
            spr_no = spr_master.spr_no
        except SPRMaster.DoesNotExist:
            spr_no = spr_item.spr_no  # Fallback to SPR number from details

        from .po_services import POCalculationService
        total_amt = POCalculationService.calculate_total_amt(
            qty, rate, discount,
            pf_id or 0, exst_id or 0, vat_id or 0
        )

        MmSprPoTemp.objects.create(
            spr_no=spr_no,
            spr_id=spr_detail_id,
            qty=qty,
            rate=rate,
            discount=discount,
            pf=pf_id,
            ex_st=exst_id,
            vat=vat_id,
            del_date=del_date,
            add_desc=remarks,
            session_id=str(request.user.id),
            comp_id=self.get_compid()
        )

        messages.success(request, 'Item added to PO successfully!')
        return redirect('material_management:po-spr-items', supplier_code=supplier_code)




class POHeaderView(MaterialManagementBaseMixin, View):
    """
    PO Step 4: Final PO Header Entry and Creation

    Shows all items from temp table, allows entering PO header details,
    and creates final PO in transaction.

    Converted from: Final step implied in PO_PR_Items.aspx (Create PO button)
    """
    template_name = 'material_management/transactions/po_header.html'

    def get(self, request, *args, **kwargs):
        supplier_code = kwargs.get('supplier_code')
        pr_spr_flag = kwargs.get('pr_spr_flag', 0)  # 0=PR, 1=SPR

        # Get temp items
        session_id = str(request.user.id)
        comp_id = self.get_compid()

        if pr_spr_flag == 1:
            temp_items = MmSprPoTemp.objects.filter(
                session_id=session_id,
                comp_id=comp_id
            )
        else:
            temp_items = MmPrPoTemp.objects.filter(
                session_id=session_id,
                comp_id=comp_id
            )

        if not temp_items.exists():
            messages.error(request, 'No items selected. Please select items first.')
            return redirect('material_management:po-new')

        # Get supplier
        from .models import Supplier
        supplier = get_object_or_404(Supplier, supplier_id=supplier_code, comp_id=comp_id)

        context = {
            'supplier': supplier,
            'temp_items': temp_items,
            'pr_spr_flag': pr_spr_flag,
        }

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """Create final PO with all items"""
        from .po_services import POCreationService

        supplier_code = kwargs.get('supplier_code')
        pr_spr_flag = int(kwargs.get('pr_spr_flag', 0))

        # Get PO header data from form
        # Convert empty strings to None for optional integer fields
        po_data = {
            'reference': request.POST.get('reference') or None,
            'reference_date': request.POST.get('reference_date') or None,
            'reference_desc': request.POST.get('reference_desc') or None,
            'payment_terms': request.POST.get('payment_terms') or None,
            'warrenty': request.POST.get('warrenty') or None,
            'freight': request.POST.get('freight') or None,
            'octroi': request.POST.get('octroi') or None,
            'mode_of_dispatch': request.POST.get('mode_of_dispatch') or None,
            'inspection': request.POST.get('inspection') or None,
            'ship_to': request.POST.get('ship_to') or None,
            'remarks': request.POST.get('remarks') or '',
            'insurance': request.POST.get('insurance') or None,
            'tc': request.POST.get('tc') or None,
        }

        # Get temp items (keep as QuerySet for delete() operation)
        session_id = str(request.user.id)
        comp_id = self.get_compid()
        fin_year_id = self.get_finyearid()

        if pr_spr_flag == 1:
            temp_items = MmSprPoTemp.objects.filter(
                session_id=session_id,
                comp_id=comp_id
            )
        else:
            temp_items = MmPrPoTemp.objects.filter(
                session_id=session_id,
                comp_id=comp_id
            )

        try:
            # Create PO using service
            if pr_spr_flag == 1:
                po = POCreationService.create_po_from_spr(
                    comp_id, fin_year_id, session_id, supplier_code, po_data, temp_items
                )
            else:
                po = POCreationService.create_po_from_pr(
                    comp_id, fin_year_id, session_id, supplier_code, po_data, temp_items
                )

            messages.success(request, f'PO {po.po_no} created successfully!')
            return redirect('material_management:po-list')

        except Exception as e:
            messages.error(request, f'Error creating PO: {str(e)}')
            return redirect('material_management:po-header', supplier_code=supplier_code, pr_spr_flag=pr_spr_flag)




class PODetailView(MaterialManagementBaseMixin, DetailView):
    """View PO Details"""
    model = POMaster
    template_name = 'material_management/transactions/po_detail.html'
    context_object_name = 'po'
    pk_url_kwarg = 'po_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # m_id is the FK to POMaster.po_id (IntegerField, not ForeignKey)
        context['po_details'] = PODetails.objects.filter(m_id=self.object.po_id)
        return context




class POUpdateView(MaterialManagementBaseMixin, UpdateView):
    """Update PO"""
    model = POMaster
    fields = ['po_no', 'po_date', 'supplier_id', 'delivery_terms', 'payment_terms', 'delivery_date', 'remarks']
    template_name = 'material_management/transactions/po_form.html'
    success_url = reverse_lazy('material_management:po-list')
    pk_url_kwarg = 'po_id'

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f'PO {self.object.po_no} updated successfully!')
        return response




class PODeleteView(MaterialManagementBaseMixin, DeleteView):
    """Delete PO"""
    model = POMaster
    success_url = reverse_lazy('material_management:po-list')
    pk_url_kwarg = 'po_id'

    def delete(self, request, *args, **kwargs):
        po = self.get_object()
        messages.success(request, f'PO {po.po_no} deleted successfully!')
        return super().delete(request, *args, **kwargs)


class POCheckActionView(MaterialManagementBaseMixin, View):
    """Check individual PO"""
    def post(self, request, po_id):
        from datetime import datetime
        po = get_object_or_404(POMaster, po_id=po_id)

        # Set check flags
        now = datetime.now()
        po.checked = 1
        po.checked_by = str(request.user.id)
        po.checked_date = now.strftime('%d-%m-%Y')
        po.checked_time = now.strftime('%H:%M:%S')
        po.save()

        messages.success(request, f'PO {po.po_no} checked successfully!')
        return redirect('material_management:po-detail', po_id=po_id)




class POApproveActionView(MaterialManagementBaseMixin, View):
    """Approve individual PO"""
    def post(self, request, po_id):
        from datetime import datetime
        po = get_object_or_404(POMaster, po_id=po_id)

        # Ensure PO is already checked
        if not po.checked:
            messages.error(request, 'PO must be checked before approval!')
            return redirect('material_management:po-detail', po_id=po_id)

        # Set approve flags
        now = datetime.now()
        po.approve = 1
        po.approved_by = str(request.user.id)
        po.approve_date = now.strftime('%d-%m-%Y')
        po.approve_time = now.strftime('%H:%M:%S')
        po.save()

        messages.success(request, f'PO {po.po_no} approved successfully!')
        return redirect('material_management:po-detail', po_id=po_id)




class POAuthorizeActionView(MaterialManagementBaseMixin, View):
    """Authorize individual PO"""
    def post(self, request, po_id):
        from datetime import datetime
        po = get_object_or_404(POMaster, po_id=po_id)

        # Ensure PO is already approved
        if not po.approve:
            messages.error(request, 'PO must be approved before authorization!')
            return redirect('material_management:po-detail', po_id=po_id)

        # Set authorize flags
        now = datetime.now()
        po.authorize = 1
        po.authorized_by = str(request.user.id)
        po.authorize_date = now.strftime('%d-%m-%Y')
        po.authorize_time = now.strftime('%H:%M:%S')
        po.save()

        messages.success(request, f'PO {po.po_no} authorized successfully!')
        return redirect('material_management:po-detail', po_id=po_id)




class POCheckView(MaterialManagementBaseMixin, ListView):
    """PO Check Dashboard"""
    model = POMaster
    template_name = 'material_management/transactions/po_check.html'
    context_object_name = 'pos'

    def get_queryset(self):
        return super().get_queryset().filter(
            comp_id=self.get_compid(),
            fin_year_id=self.get_finyearid(),
            status='Pending'
        ).order_by('-po_date')

    def post(self, request, *args, **kwargs):
        po_id = request.POST.get('po_id')
        po = get_object_or_404(POMaster, po_id=po_id)
        # Set approval flag instead of status (status is computed property)
        po.checked = 1
        po.checked_by_id = request.user.id
        po.checked_date = datetime.now()
        po.save()
        messages.success(request, f'PO {po.po_no} checked successfully!')
        return HttpResponse(status=200)




class POApproveView(MaterialManagementBaseMixin, ListView):
    """PO Approve Dashboard"""
    model = POMaster
    template_name = 'material_management/transactions/po_approve.html'
    context_object_name = 'pos'

    def get_queryset(self):
        return super().get_queryset().filter(
            comp_id=self.get_compid(),
            fin_year_id=self.get_finyearid(),
            status='Checked'
        ).order_by('-po_date')

    def post(self, request, *args, **kwargs):
        po_id = request.POST.get('po_id')
        po = get_object_or_404(POMaster, po_id=po_id)
        # Set approval flag instead of status (status is computed property)
        po.approve = 1
        po.approved_by_id = request.user.id
        po.approved_date = datetime.now()
        po.save()
        messages.success(request, f'PO {po.po_no} approved successfully!')
        return HttpResponse(status=200)




class POAuthorizeView(MaterialManagementBaseMixin, ListView):
    """PO Authorize Dashboard"""
    model = POMaster
    template_name = 'material_management/transactions/po_authorize.html'
    context_object_name = 'pos'

    def get_queryset(self):
        return super().get_queryset().filter(
            comp_id=self.get_compid(),
            fin_year_id=self.get_finyearid(),
            status='Approved'
        ).order_by('-po_date')

    def post(self, request, *args, **kwargs):
        po_id = request.POST.get('po_id')
        po = get_object_or_404(POMaster, po_id=po_id)
        # Set approval flag instead of status (status is computed property)
        po.authorize = 1
        po.authorized_by_id = request.user.id
        po.authorized_date = datetime.now()
        po.save()
        messages.success(request, f'PO {po.po_no} authorized successfully!')
        return HttpResponse(status=200)




