# Generated by Django 5.2.7 on 2025-11-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbldgMaterial',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('material', models.TextField(db_column='Material')),
                ('uom', models.CharField(blank=True, db_column='UOM', max_length=50, null=True)),
                ('comp_id', models.IntegerField(blank=True, db_column='CompId', null=True)),
                ('fin_year_id', models.IntegerField(blank=True, db_column='FinYearId', null=True)),
            ],
            options={
                'db_table': 'tblDG_Material',
                'ordering': ['material'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblmlcLivecost',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('live_cost', models.DecimalField(db_column='LiveCost', decimal_places=3, max_digits=18)),
                ('eff_date', models.CharField(db_column='EffDate', max_length=50)),
                ('comp_id', models.IntegerField(blank=True, db_column='CompId', null=True)),
                ('fin_year_id', models.IntegerField(blank=True, db_column='FinYearId', null=True)),
                ('sys_date', models.CharField(blank=True, db_column='SysDate', max_length=50, null=True)),
                ('sys_time', models.CharField(blank=True, db_column='SysTime', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblMLC_LiveCost',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
